### ISSUE TITLE
[Config] Deprecation Suggestion

### ISSUE THREAD

**Issue by llFreetimell** [Samsung/ONE-vscode#1028]
@Samsung/one-vscode_committers 

I suggest following deprecation.
Please review following suggestion.

### What

- src/Config
    ```ts
  let disposableOneConfigurationSettings =
      vscode.commands.registerCommand('one.editor.openCfgWithLegacyEditor', () => {
        ConfigPanel.createOrShow(context);
        Logger.info(tag, 'one configuration settings...');
      });
  context.subscriptions.push(disposableOneConfigurationSettings);

  createStatusBarItem(context);
    ```
- media/Config

### Why

- As cfg editor is introduced, new UI with similar look & feel of OneExplorerView is introduced.
- OneExplorerView is main entry point for ONE users but `Config` is not aligned to OneExplorerView.

---

#### Reference

- #955

**Comment by llFreetimell** [comment]
## 1st Notification

### Related Authors

- @OTKRyu 
- @SJ12896 
- @yeeybook 

### Response Deadline

- 20th July, 2022

---

Please feel free to share your opinion for the suggestion :)

**Comment by OTKRyu** [comment]
If another entry point is made and have same functions,
I'm OK with deprecation.
It's hard for me to keeping eyes on this project.

**Comment by yeeybook** [comment]
Since it makes better to develop new features, I also agree with this.

**Comment by SJ12896** [comment]
I understand. I'm okay too.

**Comment by llFreetimell** [comment]
## Final Result

### Decision

All authors of `Config` agreed to deprecate on 13th July, 2022.

### Timeline

- 13th July, 2022 : @llFreetimell Suggests to deprecate.
- 13th July, 2022 : All of the authors agreed to deprecate without any objection.
- 14th July, 2022 : Deprecated by #1030.

### Legacy

Source codes for `Config` can be found at following branch.
- https://github.com/Samsung/ONE-vscode/tree/release/0.2.0/src/Config

---

#### Comments

To @OTKRyu, @SJ12896, @yeeybook.

First of all, I wanted to say "Thank you" for you :)

Before `CfgEditor` is introduced, `Config` was the only GUI tool for cfg file.
Furthermore `Config` was helpful to fresh users because they are not familiar with cfg file iteself contrast to advanced users.

However, since `CfgEditor` is introduced, the role of `Config` is now finished :cry: 
Furthermore, because of maintenance issue, I should have removed the source codes in `main` branch :sob: 
Please kindly understand me... :(

If you have any opinion, please feel free to leave some comments at anywhere you want!
Always welcome :)
