### ISSUE TITLE
[Backend] Exchange the file names: API.ts and Backend.ts

### ISSUE THREAD

**Issue by dayo09** [Samsung/ONE-vscode#1049]
## What?

In Backend/Backend.ts,
```
function backendRegistrationApi() {
```

In Backend/API.ts,

```
export interface Backend {
  // backend's name. this doesn't mean the name of the toolchain
  name(): string;

  // compiler specs by being filled by impl
  compiler(): Compiler|undefined;

  // executor specs by being filled by impl
  executor(): Executor|undefined;
}
```

It sounds wierd that the file `Backend` has only an API, while the file `API` has only Backend definition.

Let's find out the behind story and exchange the file names.

**Comment by hyunsik-yoon** [comment]
Currently we provodes two types of API:
- API.ts defines API of which name is `Backend`, which is implemented by backend extension and called by one-vscode.
- Backend.ts defined _registration API_, which is defined in one-vscode and called by backend extension.

Some ideas I could imagine are..

- API.ts -> Backend.ts
  - interface API  // or more specific name
- Backend.ts -> BackendRegistration.ts
  - backendRegistrationApi // or just an API ?

or 

- API.ts -> BackendAPI.ts ?
  - interface API -> interface BackendAPI
- Backend.ts -> RegistrationAPI.ts
  - backendRegistrationApi

Or could we combine those two API into one file, API.ts?

**Comment by dayo09** [comment]
@hyunsik-yoon If we go with that approach, then the `Compiler.ts` and `Executor.ts` are also considered to be APIs. And I also plan to add more file like them.

I thought that most files in `Backend.ts` are those which must be implemented by backends. From the point of view, we can just leave them as is. 😃

**Comment by dayo09** [comment]
Done
