### ISSUE TITLE
[Project] Reorganization of Job codes

### ISSUE THREAD

**Issue by jyoungyun** [Samsung/ONE-vscode#1080]
### What

Let's reorganization of Job codes

### Why

To distinguish between job base codes and implementations.

### How

- [x] #1081
      - To remove the dependency with JobConfig in Job code.
- [x] #1089
- [x] #1104

**Comment by jyoungyun** [comment]
/cc @seanshpark 

As I know, @seanshpark was first designed the Project directory. 
if you see anything strange, please give me your opinion. :)

**Comment by seanshpark** [comment]
As I know, only `onecc` is called but there are Jobs that are sub tasks like `JobImport~`, `JobOptimize`, ...
Q) are these still used?

**Comment by jyoungyun** [comment]
> Q) are these still used?

AFAIK, ONE-vscode does not use several sub tasks like `JobImport~`, `JobOptimize`, etc.
Currently, we use only `JobConfig` to call `onecc`.

**Comment by jyoungyun** [comment]
Done!
