### ISSUE TITLE
[Profile] Open chrome tracer with browser

### ISSUE THREAD

**Issue by dayo09** [Samsung/ONE-vscode#1093]
## What?

Let's try opening chrome tracer with browser, especially when ssh-connection.

## Why?

To check if deprecation of json-tracer is okay.

**Comment by dayo09** [comment]
### Related library

https://www.npmjs.com/package/opn

- MIT license
- Support cross-platform url opening
- Includes the latest xdg-open in linux

**Comment by yunjayh** [comment]
[vscode chrome trace viewer](https://github.com/jacobdweightman/vscode-chrome-trace-viewer) extension opens http server with temp directory. 
Since perfetto can be loaded with file's uri as it's parameter, it does works. 
(`https://ui.perfetto.dev/#!/?url=http://127.0.0.1:9001/trace.json` will open my trace.json via perfetto)

**Comment by hyunsik-yoon** [comment]
@yunjayh Good info.

I tried to find more info about perfetto.

https://perfetto.dev/
"Runs fully in your browser"
"No server interaction involved, works even if you are offline"

https://perfetto.dev/docs/#trace-visualization
"The Perfetto UI works fully offline after it has been opened once. Traces opened with the UI are processed locally by the browser and do not require any server-side interaction."

**Comment by hyunsik-yoon** [comment]
- Similar try in android source code (Apache 2): https://cs.android.com/android/platform/superproject/+/master:external/perfetto/tools/open_trace_in_ui;l=58-76.

- In SSH-Extension env, the IP should be ubuntu machine's IP. 

- [Like shown in this code, ](https://github.com/jacobdweightman/vscode-chrome-trace-viewer/blob/main/src/extension.ts#L19) it opens web server without considering CORS. 

- [Another way around could be this one](https://perfetto.dev/docs/visualization/deep-linking-to-perfetto-ui).

- I wonder if opening temporal web server could be secure or not. However, there are some programs that opens web server: e.g., Tensorboard.

**Comment by yunjayh** [comment]
Thank you for your detailed research!!!! 

> * I wonder if opening temporal web server could be secure or not. However, there are some programs that opens web server: e.g., Tensorboard.

+1 to this thought. But, as you can find in the main comment of this issue, I'm not sure how to solve the problem in case of using ssh-extension.

**Comment by dayo09** [comment]
> I'm not sure how to solve the problem in case of using ssh-extension.

Same here..

I tried porting [vscode chrome trace viewer](https://github.com/jacobdweightman/vscode-chrome-trace-viewer) extension.
It works well locally but not with ssh-extension

**Comment by dayo09** [comment]
FYI, they say

- embedding with iframe is not supported, and never planed to, because of security reasons [:link](https://github.com/google/perfetto/issues/14#issuecomment-917666287)
- vulcanization is not supported, not planned either [:link](https://github.com/google/perfetto/issues/14#issuecomment-974464246)

**Comment by dayo09** [comment]
#### Opening the main page is okay:

Because npm/open is a cross-platform network tool, we can open the `ui.perfetto.dev` main page in ssh. 

#### However, Loading the file is...

It seems they only provides an api of https://perfetto.dev/docs/visualization/deep-linking-to-perfetto-ui.
It assumes 'javascript, page-to-page communication'. Therefore assumes window.open and Window.postMessage apis. We should

(1) wait for the page to be ready
(2) put postMessage() with a buffer of our trace data

I am trying to find if there is any workaround, trying such things as 'window-post-message-proxy'...

**Comment by dayo09** [comment]
#### Opening the pages via webview: impossible

vscode doesn't allow webview to open an url outside. They intentionally blocks modals. 
```window.open()``` <- impossible within webview, too.

**Comment by llFreetimell** [comment]
After seeing your huge efforts... I think this issue cannot be achieved before release T.T
(I even failed to open main page on the panel...)

**Comment by dayo09** [comment]
@llFreetimell 

It seems 'perfetoo' has blocked itself from 'iframe', for a security reason. AND, vscode extension api document says 'webview' is a kinda 'iframe'. So it shoudn't show up. 
I only succeeded in opening the main page on the browser, too...

**Comment by dayo09** [comment]
To summarize so far, 

(1) perfetto maintainers don't aim to support 'vulcanization'(synthethically embedding into other project) because of security reason.
(2) vscode extension basically supports embedding by iframe. 
- they don't allow pop-up on webview, too.

Therefore, embedding looks to be impossible.

**Comment by hyunsik-yoon** [comment]
Thanks for @dayo09's work.
I will also spend some time figure this out. :-)

**Comment by hyunsik-yoon** [comment]
Can we open a json in Chrome Tracer without clicking `load` button?
- https://stackoverflow.com/questions/49147681/load-json-manually-in-chrome-tracing
  - Automate the drag & drop could be implemented 
    - We need Javascript knowledge
    - Handling json file in SSH Extension env is still questionable

**Comment by hyunsik-yoon** [comment]
1. a single linux box (not SSH-extension env)
- When I try `open(https://ui.perfetto.dev/#!/?url=http://127.0.0.1/trace.json)`, perfetto shows the file really well.

2. SSH-extension env
I put json file in my linux PC (IP is, say, 10.11.12.13).
- `open(http://10.11.12.13/trace.json)` works and my browser shows raw json file. So there seems no company-internal-complex-network issue.
- `open(https://ui.perfetto.dev/#!/?url=http://10.11.12.13/trace.json)` fails. perfetto web site shows `"Oops, something went wrong. Please file a bug. (Googlers only)"` message.

**Comment by dayo09** [comment]
> Other way around to use perfetto is using popup window (window.open()). @dayo09 already found that this didn't work either in vscode (https://github.com/Samsung/ONE-vscode/issues/1093#issuecomment-1197734019).
> 
> It seems like perfetto is not an option.

So it came to the same conclusion. Let's go with #1135 instead.
