### ISSUE TITLE
 Questions about open source licenses

### ISSUE THREAD

**Issue by CODe1995** [Samsung/ONE-vscode#11]
![image](https://user-images.githubusercontent.com/47562093/131290998-f3a276a7-ee81-4f2e-97f3-bb5abdda21f2.png)

I am trying to use an **open source chart library**, but it is marked like the image above.
If `private use` is listed, is it not possible to use it in our project?

**Comment by llFreetimell** [comment]
Can you state which library is it? I want to check which license type is used for the library :)

**Comment by yesfordev** [comment]
https://github.com/recharts/recharts/blob/master/LICENSE

This chart library! :)

**Comment by llFreetimell** [comment]
MIT License seems ok :)

But one more check!
Do you want to use the code itself in https://github.com/recharts/recharts or just use the package itself?
More specifically, which one is what you want between following options?

- I want to copy & paste the code in https://github.com/recharts/recharts to out repository
- I want to just import recharts library like `require(recharts)`

**Comment by yesfordev** [comment]
I want to just import recharts library like require(recharts) :)

**Comment by llFreetimell** [comment]
Then it seems to have no problem :)
I will let you know later if there were some missing points!

**Comment by CODe1995** [comment]
The question has been resolved. thank you.
