### ISSUE TITLE
Deprecate one.backend.infer cmd?

### ISSUE THREAD

**Issue by hyunsik-yoon** [Samsung/ONE-vscode#1118]
AFAIR, We implemented `one.backend.infer` for first release to show feasibility to call backend inference cmd.
I wonder if we need this code in Aug release.
If now, how about remove relate code regarding `one.backend.infer`?

/cc @yunjayh

**Comment by yunjayh** [comment]
As you commented, it was introduced for temporal feasibility test. IMO, it's needed to deprecate the codes before the release. 

Since I'm in training course until Thursday, it will be glad if someone participates to deprecate the codes.

**Comment by hyunsik-yoon** [comment]
Done.
