### ISSUE TITLE
Format custom editor viewTypes

### ISSUE THREAD

**Issue by dayo09** [Samsung/ONE-vscode#1165]
Related to #728

## What?

Let's format our viewType names as 
`one.view.\<type\>`
`one.viewer.\<type\>`
`one.editor.\<type\>`

(view or viewer or editor)

1. `one.` prefix
- Use `one` instead of `onevscode` as our extension's official name is 'one'
2. `\<view\>.\<type\>`

## Targets

current name | suggestion | etc
---|---|---
onevscode.mondrianViewer | one.viewer.mondrian
onevscode.part-editor | one.editor.part
onevscode.circleViewer | one.viewer.circle
cfg.editor | one.editor.cfg
JsonTracer | one.viewer.jsontrace
one.viewer.jsonTracer | one.viewer.jsontrace.open | not a viewtype, open command for the panel

**Comment by hyunsik-yoon** [comment]
I like such renaming. :-)
/cc @seanshpark @ai-moiseev

**Comment by dayo09** [comment]
Done :-D
