### ISSUE TITLE
Perform v0.3.0 release

### ISSUE THREAD

**Issue by yunjayh** [Samsung/ONE-vscode#1187]
Let's perform v0.3.0 release

---

# Checklist

## Release Action

- **Before branch out**
- [x] Release Note #1188
- [x] Update Version #1193 
- **After branch out**
- [x] Make tag
- [x] Release Issue (dispatch from github action)

## Release Package
- [x] ONE-vscode package

## Release Criteria

- [x] SAM
- [x] CQM
- [x] TEM
- [x] TCM
- [x] License Verification

/cc @llFreetimell

**Comment by jyoungyun** [comment]
How about using one commit for Update version and release note? If it is divided into several commits, there is a possibility that other commits will be added in the meantime. And it will be difficult to grasp the release-related commits at a glance.

**Comment by yunjayh** [comment]
> How about using one commit for Update version and release note? If it is divided into several commits, there is a possibility that other commits will be added in the meantime. And it will be difficult to grasp the release-related commits at a glance.

It sounds good. I'll merge two prs to one and update it.

**Comment by yunjayh** [comment]
v0.3.0 has been released. Thank you for your great works, @Samsung/one-vscode.

Let's close this and keep focus on the other issues. :tada:
