### ISSUE TITLE
Question about using framework to create backend output visualization page.

### ISSUE THREAD

**Issue by yesfordev** [Samsung/ONE-vscode#12]
To visualize the json file, which is backend output, we want to use webview in visual studio extension, and we want to implement it using the React.js framework in webview, is that okay?

If we use React.js, we want to use the relevant chart library that uses React.js. :)

**Comment by llFreetimell** [comment]
@yesfordev 

Concern about license and copyright is handled in #11 :)
Except this one, do you have another questions or concerns?

**Comment by yesfordev** [comment]
No, i don't have any questions :) Thank you!

**Comment by llFreetimell** [comment]
You can close this :D

**Comment by yesfordev** [comment]
There is no more problem to solve, so I will close this issue. :)
