### ISSUE TITLE
[Visualization] How can I read nodes of a circle model using JS?

### ISSUE THREAD

**Issue by kevin622** [Samsung/ONE-vscode#121]
Hi! I'm 국현 from team COSMOS. We are currently developing a tool which would be named Circle-OpSelector. ([here](https://github.com/Samsung/ONE/issues/7596) is our main issue)

I'm trying to develop a tool that can __visualize__ the operation(the Circle-OpSelector), so I'm using `Vue` to create an browser based app. Here, I'm having a problem reading information of a Circle model.

Below is `App.vue`, created to check whether the model was read properly.
```vue
<template>
  <div>
    <input type="file" ref="files" @change="fileInputChange">
  </div>
</template>

<script>
/* eslint-disable */
import * as circleFlatbuffers from '../../flatbuffers/circle/flatbuffers.ts'

export default {
  name: 'App',
  methods: {
    async fileInputChange () {
      // file input (circle)
      const file = this.$refs.files.files[0]

      // change the input file to arrayBuffer
      const arrayBuffer = await file.arrayBuffer()

      // change the arrayBuffer to Uint8Array
      const bytes = new Uint8Array(arrayBuffer)

      // change the Uint8Array to flatbuffers
      const buf = new circleFlatbuffers.ByteBuffer(bytes);

      // Import the Model Class
      const Model = require('../../flatbuffers/circle/model').Model

      // Create a Model instance
      const model = Model.getRootAsModel(buf);

      // Check the operators of the model
      for(let i=0; i < model.operatorCodesLength(); i++) {
        console.log(`#${i} operator code;`, model.operatorCodes(i).builtinCode())
      }

      // Check the description of the model
      console.log('description;', model.description())

      // Check the buffers(?) of the model
      console.log('buffersLength;', model.buffersLength()) 
      for(let i=0; i < model.buffersLength(); i++) {
        const buffers = model.buffers(i)
        console.log('buffers; ', buffers.dataArray())  
      }
      
    },
  }
}
</script>

<style>
</style>

```

Here I want to access the nodes, but I'm not sure how to. I'm guessing that the `buffers` contain all information regarding each node, but I don't know how to understand it.
I found that in #66, your team succeeded in visualizing a model. Can you inform me of the way to read the __node information__ of a model?

I appreciate your help in advance. 🙇 

_ps. The reason why I'm developing from scratch and not using the codes in [Netron](https://github.com/lutzroeder/netron) is because since we are developing a new operation(Circle-OpSelector), I wanted to make sure I'm aware of all the codes in the visualization app, so I know where to apply the operation code._

**Comment by llFreetimell** [comment]
At first, you should look at https://github.com/Samsung/ONE/blob/master/nnpackage/schema/circle_schema.fbs and figure out the file structure :)
Fortunately, I think you knows how to access the each data.
So I hope following short hint helps you!

- The file starts from `Model`
- `Model` has `Subgraph`
- `Subgraph` has `Operator`
- `Operator` has
  - `opcode_index` : indicates what kind of operator
  - `builtin_options` : indicates what kind of `BuiltinOptions` is used
  - ...

**Comment by kevin622** [comment]
@llFreetimell 
Thanks for your advise! I'm currently following your instructions, and it seems the problem that I was facing is solved. I'll close this issue, hence.
