### ISSUE TITLE
[OneExplorer] File System Watcher is not working on ssh-remote

### ISSUE THREAD

**Issue by dayo09** [Samsung/ONE-vscode#1213]
## What?

OneExplorer's fileSystemWatcher is not working on ssh-remote, reported by @llFreetimell, @hyunsik-yoon 

(I cannot reproduce it from my ssh-remote envs 😭)

**Comment by dayo09** [comment]
Q. Have you guys set your vscode environment setting 'files.watcherInclude' or 'files.watcherExclude' to somethign..?

**Comment by hyunsik-yoon** [comment]
In my case no setting on `files.watcherInclude` but excluded the following
```
    "files.watcherExclude": {
        "**/build/compiler": true,
        "**/compute/**": true,
        "**/deps/**": true,
        "**/docs/compiler": true,
        "**/externals/**": true,
        "**/infra/applet/**": true,
        "**/Product/**": true,
        ".venv": true,
        "node_modules": true,
    },

```

**Comment by dayo09** [comment]
@hyunsik-yoon Thanks for sharing :-D I cannot find a clue yet.. I may ask you to share your environment later. Thanks!

**Comment by dayo09** [comment]
### Another Issue Found: Directory removal is not detected (local, too)

It's found out that removing directory within the workspace is not detected, both on ssh-remote or local envs.

**Comment by dayo09** [comment]
@hyunsik-yoon has shared the detail of error cases:

On his ssh-remote env,
- [ ] Directory deletion is not detected. (-> Issue Re-defined)
- [ ] File move is not detected. (ex. mv model.tflite model2.tflite)

(@llFreetimell Could you share the details of your cases, too?)

**Comment by dayo09** [comment]
@llFreetimell He has shared me the env as:
He opened **the ssh-remote-connected vscode window** and **the local linux file system explorer** both at the same time.
And,  he's vscode default explorer were not being refreshed automatically, too.

===> IT SEEMS vscode ssh extension does NOT support file system watcher when the file system is opened in other site. 
 
Awaring the limitation of vscode's file system watcher, let's close this issue.
