### ISSUE TITLE
[OneExplorer] Support preview of editors

### ISSUE THREAD

**Issue by dayo09** [Samsung/ONE-vscode#1228]
## What?

Let's support 'preview' for editors.
@lemmaa 

### What is 'preview'?

![0823-preview-explain](https://user-images.githubusercontent.com/17171963/186146047-d1923f88-0fd2-446a-8c13-3638c8bea8c0.png)

A supported feature which doesn't 'keep open' the file, but only preview in a volatile tab in default explorer window.

### How?
https://code.visualstudio.com/api/references/commands
![0823-command-reference](https://user-images.githubusercontent.com/17171963/186145434-2cea5ca7-b0bf-484d-ab2e-890fc118c05c.png)

https://code.visualstudio.com/api/references/vscode-api#TextDocumentShowOptions
![0823-options](https://user-images.githubusercontent.com/17171963/186145568-16e3a136-c71a-4026-acef-ab5695364617.png)
sualstudio.com/api/references/vscode-api#TextDocumentShowOptions

From the references above, I expected the below code to make 'preview' feature to be enabled.
![0823-preview](https://user-images.githubusercontent.com/17171963/186145676-787708af-8b0d-44a5-b5f6-29525e9e0a34.png)
However, it didn't. :cry: Let's find out the way.

**Comment by dayo09** [comment]
### VSCode feature request status: They are working on it

https://github.com/microsoft/vscode/issues/154145

In this July,  it seems the features is requested and with abundant upvotes, it is selected and being implemented by the team.

**Comment by lemmaa** [comment]
> So, currently there is no way to support this feature. Let's wait until they finish it.

Can't it be applied in advance to "Open with Text Editor" in the context menu? :)

**Comment by dayo09** [comment]
@lemma I think it is possible to provide it as a unique command as its' a tree view's problem that not supporting the command options. I will try :-D

**Comment by dayo09** [comment]
### Problem :openWith command not working with TextDocumentShowOptions for CfgEditor

It seems that openWith command's optional `TextDocumentShowOptions` is not working.
(Maybe it's my vscode version..?)


The 'TextDocumentShowOptions', which is documented in the official API, is originally for showTextDocument function.
I have tested the function as below, and it WORKS WELL.
HOWEVER, with openWith command, the option is not working at all (even with default text editor)

```
            vscode.window.showTextDocument(oneNode.node.uri, {preview:true});
```

**Comment by dayo09** [comment]
> 
> 
> ```
>       vscode.commands.registerCommand(
>           'one.explorer.previewCfg',
>           (node: Node) => {
>             vscode.window.showTextDocument(node.uri, {preview:true});
>             //vscode.commands.executeCommand('vscode.openWith', node.uri, 'default', {preview:true});
>           }),
> ```
> 
> - `vscode.window.showTextDocument(node.uri, {preview:true})` works well, it opens the text document as 'preview'
> - `vscode.commands.executeCommand('vscode.openWith', node.uri, 'default', {preview:true})` doesn't work, it opens the text document as 'open'.
> 

It seems that showTextDocument only takes `showTextDocumentOptions` which includes 'preview' option. Therefore, for CustomTextEditor documents like CfgEditor cannot use this API.

_Originally posted by @dayo09 in https://github.com/Samsung/ONE-vscode/issues/1232#issuecomment-1293287005_

**Comment by dayo09** [comment]
We cannot support this feature for now. Let's close this issue.
