### ISSUE TITLE
[CI] Add no-body-check

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE-vscode#123]
We need to check commit message is OK

**Comment by seanshpark** [comment]
#122 has no message body.

**Comment by llFreetimell** [comment]
@seanshpark Can I take this? :)

**Comment by seanshpark** [comment]
> Can I take this? :)

Yes! please do :)

**Comment by llFreetimell** [comment]
### What?

Let's enable commit message checker in Github Action!

### Why?

Some of members are new to create pull requests in ONE-vscode.
So the member may write commit message only with title.
Let's reduce such mistake by commit message checker!

### Todo

- [ ] Create a script file to check commit message
- [ ] Enable it in Github Action

#### Draft

- TBA

**Comment by llFreetimell** [comment]
Done!
