### ISSUE TITLE
[OneExplorer] About deprecating 'rename' command

### ISSUE THREAD

**Issue by dayo09** [Samsung/ONE-vscode#1233]
## What?

@lemmaa has pointed out that 'rename' functionality may confuse users, rather than it promotes the usability.
Let's talk about whether to keep the command or deprecation.

**Comment by dayo09** [comment]
Please vote here

❤️ : Let's keep it.
🚀 : Let's deprecate it.

**Comment by hyunsik-yoon** [comment]
+1 for deprecating current impl
+1 for changing current 'rename' to 'rename' as refactoring feature (e.g., renaming tflite will change the tflite name in cfg file)

:-)

**Comment by dayo09** [comment]
@hyunsik-yoon It's a cool summary. Thanks!
