### ISSUE TITLE
[Questions] Does all the src sub-files have to be TS?

### ISSUE THREAD

**Issue by wnsdud4197** [Samsung/ONE-vscode#124]
We are visualizing using a webview.
React has several issues (license, package.json etc...), so we made it vanilla js.
js is a script that only works in webview.
It cannot access the main VS Code APIS directly.

Is it okay to add the js file to the src sub-folder?

**Comment by seanshpark** [comment]
> js is a script that only works in webview.

Is the `js` you mentioned to be the js file(s) of `vanilla js` ?

**Comment by seanshpark** [comment]
> js is a script that only works in webview.
It cannot access the main VS Code APIS directly

You mean, these `js` files are only used (executed) in `webview` ?

**Comment by wnsdud4197** [comment]
>Is the js you mentioned to be the js file(s) of vanilla js ?

yes, the js file(s) of `vanilla js`.

> You mean, these js files are only used (executed) in webview ?

yes, it's only used in `webview`.

**Comment by seanshpark** [comment]
> yes, the js file(s) of vanilla js.
> yes, it's only used in webview.

background: I don't know much about vscode extension development. so I don't know it is OK or not, that is I don't know how other extensions manage files.

If these `js` files are not called used from vscode, then why put them in `src` folder?
There is draft/PRs that put css files in `media` folder and in that perspective, can we put these `js` files in `media` ?

**Comment by wnsdud4197** [comment]
The location doesn't matter whether it's media or src, but it seemed better to make it under src to manage it. If they use the media folder elsewhere, it's not a problem at all to move it.

Shall we move to the media folder?

**Comment by seanshpark** [comment]
> , but it seemed better to make it under src to manage it. 

Can I ask what kind of management you are thinking?

**Comment by wnsdud4197** [comment]
In my opinion,

I thought it would be better to put all the files that perform the function in one folder.

Our project has many functions in one extension, and I thought it might be difficult to read if it was managed through multiple folders of each function.

**Comment by OTKRyu** [comment]
i tried to manage static files for webview in media and tried to manage typescript files that directly use vscode extension in src.
i don't know it's great way but it can be one way to manage files.
and i think there is reason for vscode-extension-webview sample choose this way

**Comment by seanshpark** [comment]
> put all the files that perform the function in one folder.

My thought is different. This depends on the purpose and how the files are used.
As I understand, typescript source files are source for logic of extension itself.
the `js` files you mention are scripts used to control the view of the extension.

Why I think different is that if we map these to node application (I'm not sure I understand this correctly...)
typescript -> js files work as service side of node.
`js` files you mention are client side, which runs in the browser.

So in this analogy, purposes are differnent, so management would be better in different.

**Comment by wnsdud4197** [comment]
Thank you for your answer.🙏

Then, we will create a folder under `media` and manage `JS` files.

**Comment by wnsdud4197** [comment]
I will close this issue because it has been discussed enough, and i have received the desired answer.
