### ISSUE TITLE
Can we 'Run onecc' without installing a Backend-side extension?

### ISSUE THREAD

**Issue by dayo09** [Samsung/ONE-vscode#1250]
## What?

When we click 'run onecc' button without installation of the backend-side extension, it only generates an error message.

I wonder if we have any ways to take a shortcut to use 'run onecc' command without supporting a.k.a dummy-backend. 

Let's find some ways.

/cc @jyoungyun @hyunsik-yoon  @Samsung/one-vscode

**Comment by hyunsik-yoon** [comment]
It seems like a good point to consider.

If user installs ONE (https://github.com/Samsung/ONE/releases/tag/1.20.0) 
it might be natural to think that backend extension is not needed to compile, e.g., model.onnx to model.opt.q8.circle file,
which we don't have right now......

**Comment by jyoungyun** [comment]
At this time, the toolchain cannot be installed unless the Backend extension is installed. In the ONE dockerizing SSAFY project, ONE toolchain will be installed without a Backend extension to support the use of `run onecc` without a backend.

/cc @Samsung/ssafy_2022

**Comment by dayo09** [comment]
@jyoungyun 

> ONE toolchain will be installed without a Backend extension to support the use of run onecc without a backend.

Do you have any plan for this? Or even a rough idea..?

/cc @Samsung/andrometa

**Comment by jyoungyun** [comment]
Um, ONE Toolchain Backend will be introduced by using `one-docker` debian package (The package name is not fixed yet.). The ONE Toolchain Backend will install the `one-compiler` in the user's environment using other things. This installed toolchain can even proceed to create a circle model file using `onecc`. If you want to do things like `codegen` or `profile`, you need to install the backend toolchain.

What is the andrometa team trying to to with this work?

**Comment by dayo09** [comment]
#1295 is implemented, I am closing this issue.
