### ISSUE TITLE
[ootpg] Where does register backend api work?

### ISSUE THREAD

**Issue by lettersto** [Samsung/ONE-vscode#1265]
Hi, I'm Hyeryeong from team ootpg (from SSAFY; Samsung SW Academy For Youth).
We're currently developing that users can use toolchains without backend-side extensions using docker container (see #1250). (Plus, we’re going to upload an issue on our plan soon.)

Now we have some trouble finding the place where ONE-vscode can notice our dummy Backend. We have figured out, we need to register some Backend to develop and this works with `API.ts`. But, we don’t know where to register our Backend exactly. 

1. Do we have to “hard-code” like `registrationAPI.registerBackend(DummyBackend)` somewhere?
(You can see this code in github too → [click link](https://github.com/Psalmist-KIM/ONE-vscode/blob/main/src/Backend/API.ts)
    
    ```tsx
    // src/Backend/API.ts
    function backendRegistrationApi() {
      const logTag = 'backendRegistrationApi';
    
      let registrationAPI = {
        registerBackend(backend: Backend) {
    
          const backendName = backend.name();
          assert(backendName.length > 0);
          globalBackendMap[backendName] = backend;
          const compiler = backend.compiler();
          if (compiler) {
            gToolchainEnvMap[backend.name()] = new ToolchainEnv(compiler);
          }
          const executor = backend.executor();
          if (executor) {
            globalExecutorArray.push(executor);
          }
          Logger.info(logTag, 'Backend', backendName, 'was registered into ONE-vscode.');
          // NOTE: This might not 100% guaratee the activating extension has been done.
          //   - link: https://github.com/Samsung/ONE-vscode/pull/1101#issuecomment-1195099002
          // TODO: Consider better way to refresh toolchainView after backend's registration.
          vscode.commands.executeCommand('one.toolchain.refresh');
          vscode.commands.executeCommand('one.device.refresh');
        },
        registerExecutor(executor: Executor) {
          globalExecutorArray.push(executor);
          Logger.info(logTag, 'Executor', executor.name(), 'was registered into ONE-vscode.');
        }
      };
    
      registrationAPI.registerBackend(DummyBackend);
    
      return registrationAPI;
    }
    ```
    
2. Or does it calls `registerBackend` automatically? If so, when does ONE-vscode register Backend?
    1. In `extension.ts` `activate` function calls `backendRegistrationApi()` and returns `registrationAPI`. Does it has somethig to do with question 2? We don’t understand what `backendRegistrationApi()` ’s return values do.

/cc **[@Samsung/ootpg](https://github.com/orgs/Samsung/teams/ootpg)**

**Comment by mhs4670go** [comment]
I don't know the details but let me have one question. Why do we need a dummy backend? If we want to run `onecc` without backend extension, can't we just make them the way we want to do rather than having dummy backend?

**Comment by jyoungyun** [comment]
First approach is right. :)

> I don't know the details but let me have one question. Why do we need a dummy backend? If we want to run onecc without backend extension, can't we just make them the way we want to do rather than having dummy backend?

I don't think they make a dummy backend. They seem to understand the code by looking at the use of dummy backend in the test before implementing the codes. Maybe in the future, ONE Toolchain backend will be created instead of dummy backend. Is it right? 

/cc @Samsung/ootpg

**Comment by mhs4670go** [comment]
> I don't think they make a dummy backend. They seem to understand the code by looking at the use of dummy backend in the test before implementing the codes.

Understood:)

> Maybe in the future, ONE Toolchain backend will be created instead of dummy backend. Is it right?

I think you used the word "ONE Toolchain backend" as a tool that only includes `onecc` without any backend things; without any codegen driver. But sounds to that it could be misleading word because "ONE Toolchain" runs "backned" drivers. It means that ONE Toolchain's backend could be for dummy or for npu or etc.

Of course it is controversial. Please let me know if you have any comments:)

**Comment by lettersto** [comment]
> They seem to understand the code by looking at the use of dummy backend in the test before implementing the codes.

Yes. We are not 100% sure what ONE Toolchain backend is, we just want to understand before implementing codes. So we asked about that.

> But sounds to me that it could be misleading word because "ONE Toolchain" runs "backned" drivers. It means that ONE Toolchain's backend could be for dummy or for npu or etc.

That’s what we wanted to question too :)

The reason why we asked those questions above is…
    1. When we install released debian package from ONE, we can use CLI commands to use onecc.
    2. But still, we don’t see any GUI change in ONE-vscode at all, especially under TOOLCHAIN view on left sidebar.
    3. So, we assume, what we’re going to do is to show users abstracted toolchain (like onecc-docker-toolchain) under TOOLCHAIN view. 
    
And by doing so - call `registrationAPI.registerBackend(DummyBackend);`  inside `API.ts` -, we could see our dummy backend under TOOLCHAIN view. That’s why we asked those questions.

**Comment by mhs4670go** [comment]
> What is the appropriate name for our toolchain backend?
> Therefore, I think it can be a `ONE Toolchain`, a set of programming tools used to perform `onecc` command line tool.

Oh, I also think `ONE Toolcahin` is appropriate. The word that I think was inappropriate is "backend".

**Comment by jyoungyun** [comment]
> Oh, I also think `ONE Toolcahin` is appropriate. The word that I think was inappropriate is "backend". 

Ah! Okay I've got it. :)

What do you think of `ONE Toolchain` as a backend name?

/cc @Samsung/ootpg

**Comment by lettersto** [comment]
We think, ONE Toolchain would be better for understanding. And can we close the issue, since it seems all questions are solved :)

**Comment by lettersto** [comment]
It seems all questions are solved. Let's close the issue.
