### ISSUE TITLE
[Meta Provider] Could you provide more dummy files?

### ISSUE THREAD

**Issue by gandi0330** [Samsung/ONE-vscode#1279]
## What
I think We need more dummy circle, model, and log files 

## Why
dummy files must be created to test the metadata manager's function

For example, we create metadata through dummy data, and we query the relationship of dummy data through metadata

## Then
so we need this dummy files

The relationship structure created with the current resources is as follows.
(The log file was created at random)

![image](https://user-images.githubusercontent.com/67681207/190303364-80992046-828e-4103-af5e-835789c9507a.png)

But I think the resources for the test are at least...

![image](https://user-images.githubusercontent.com/67681207/190303316-be8a3e8a-3d9f-4ca1-94a7-e3a310a50a45.png)

---

In fact, since it is a test file, I can create a relationship randomly through metadata as long as the number of files is correct regardless of the relationship.

But if possible, I would like to get example files that are related like the picture above.

**Comment by dayo09** [comment]
Sorry for the late reply, I was out of office for the days.
It seems not difficult to add the examples, I will create a PR for that :-D

**Comment by dayo09** [comment]
Sorry for the late response, as I passed the files by hand, let's close this issue :-D
