### ISSUE TITLE
[CircleEditor] Custom Operator Edit - Float issue

### ISSUE THREAD

**Issue by YuHyeonwoo** [Samsung/ONE-vscode#1296]
Related PR #1293 

### Main
If I change the type of Attribute value from float or int to other types and save Attribute data, "Int" type turns into "bigInt" type.

### Example
- The data requested to be saved
    - a_x : 1 (int), a_y : 0.12345 (float), T12 : 3 (int)
- data is actually saved as follows
    - {T12: 3n(bigint), a_x: 1n(bigint), a_y: 0.12345(float)}
 
### Test Method
We want you to test this issue as follows.
1. Run extension and open while_000.circle using our extension #1262
2. Click 'Attribute 수정 버튼' and then push "ctrl + s" so that this data can be saved.
3. Open circle file using "Circle Viewer" and you can find that the data is turned into strange numbers.
4. You can check the saved data of circle resource by looking console after clicking "커스텀 정보 보내기 버튼".

You can edit the test sample data by editing the message of the postMessage function.
>File Path : './media/CircleEditorTest/index.html' (43 ~ 57)

You can check my custom_operator Edit logic through 'AttributeEdit' function.
>File Path : './src/CircleEditor/CircleEditorDocument.ts' ( 354 ~ 403 )

If you want to check the circle's data, you will should 'SendcustomType' function.
>File Path : './src/CircleEditor/CircleEditorDocument.ts' ( 132 ~ 167 )

**Comment by llFreetimell** [comment]
Hmm... I got following result.

```
key : custom
value : 97, 95, 120, 0, 97, 95, 121, 0, 84, 49, 50, 0, 3, 5, 14, 11, 3, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 124, 242, 176, 80, 107, 154, 191, 63, 4, 4, 15, 27, 39, 1
```

How can I check `{T12: 3n(bigint), a_x: 1n(bigint), a_y: 0.12345(float)}` ?

**Comment by llFreetimell** [comment]
`n` in `1n` means `bigint` in typescript grammar.
(it's like that `LL` in `1LL` means `long long int` in C++)

The reason why `n` is appended is because `addInt(number)` is same with `add(bigint)`.
This means that integer type for flexbuffers in typescript is handled as `bigint` by default.
So it seems that no problem :)

**Comment by YuHyeonwoo** [comment]
Thanks your comment!

If custom_operator's value is changed type the `bigint`, The Viewer happen error!

It can't show `key : value`, It show only `'custom' : flexbuffer` encoding data (`int Array`).

Should the GUI's logic handle this problem?

**Comment by llFreetimell** [comment]
Original netron code is handling it.

https://github.com/Samsung/ONE-vscode/blob/56dfc0f424f5ca8fb5434a8421ed5c1846bf9792/media/CircleGraph/external/circle.js#L327-L359

I think it's because not correctly decoded because of some reason :(

**Comment by llFreetimell** [comment]
I found the implementation error :)
Following code works..!

```ts
			for(const key of custom_key){
				fbb.addKey(key);
				fbb.add(data._attribute[key]);
				// if(val_type === "boolean"){
				// 	if(val === "true"){
				// 		fbb.add(true);
				// 	}
				// 	else{
				// 		fbb.add(false);
				// 	}
				// }
				// else if(val_type === "int"){
				// 	console.log("int");
				// 	fbb.addInt(Number(val));
				// }
				// else if(val_type === "float"){
				// 	console.log("float");
				// 	fbb.addFloat(Number(val));
				// }
				// else{
				// 	console.log("string");
				// 	fbb.add(String(val));
				// }
			}
```

**Comment by YuHyeonwoo** [comment]
When I get a data from GUI, All data's type is `string` ( GUI's team can't know about custom operator value's type )
So, If I change your code, All data's types are `string`. So, custom_operator value's data is changed compare to origin data.
I think that custom_operator data contain data's type. I'll show you one example

file : #1262 

origin custom operator data : `(30) [97, 100, 106, 95, 120, 0, 97, 100, 106, 95, 121, 0, 84, 0, 3, 3, 16, 11, 3, 1, 3, 0, 1, 0, 4, 104, 104, 6, 36, 1]`
(adj_x : true `bool`, adj_y : false `bool` , T : 0 `int`)
same key, value but, type is string : `(36) [84, 0, 97, 100, 106, 95, 120, 0, 4, 116, 114, 117, 101, 0, 97, 100, 106, 95, 121, 0, 3, 21, 20, 9, 3, 1, 3, 0, 19, 0, 4, 20, 104, 6, 36, 1]`
(adj_x : true `string`, adj_y : false `bool` , T : 0 `int`)

So, I think when i save the data using `flexbuffer`, we consider about value's type!! :'(

**Comment by llFreetimell** [comment]
Then following codes would work :)

```ts
fbb.addKey(key);
let val = data._attribute[key];
const val_type = data._attribute[key+"_type"];
if(val_type === "boolean"){
	fbb.add(val as boolean)
	// if(val === "true"){
	// 	fbb.add(true);
	// }
	// else{
	// 	fbb.add(false);
	// }
}
else if(val_type === "int"){
	console.log("int");
	fbb.add(val as number);
}
else if(val_type === "float"){
	console.log("float");
	fbb.add(val as number);
}
else{
	console.log("string");
	fbb.add(val as string);
}
```

Please note that `Number` and `number` is different type!

**Comment by YuHyeonwoo** [comment]
All data type's also is saved using this code :'(

So, we are thinking about excluding `float`...

**Comment by llFreetimell** [comment]
> So, we are thinking about excluding float...

What do you mean?
Only `float` is problem or all other types are problem?

**Comment by llFreetimell** [comment]
> I think that custom_operator data contain data's type. I'll show you one example


> origin custom operator Attribute data : (30) [97, 100, 106, 95, 120, 0, 97, 100, 106, 95, 121, 0, 84, 0, 3, 3, 16, 11, 3, 1, 3, 0, 1, 0, 4, 104, 104, 6, 36, 1]
(adj_x : true bool, adj_y : false bool , T : 0 int)
same key, value but, type is string : (36) [84, 0, 97, 100, 106, 95, 120, 0, 4, 116, 114, 117, 101, 0, 97, 100, 106, 95, 121, 0, 3, 21, 20, 9, 3, 1, 3, 0, 19, 0, 4, 20, 104, 6, 36, 1]
(adj_x : true string, adj_y : false bool , T : 0 int)

And can you let me know how did you get this result?

**Comment by YuHyeonwoo** [comment]
<img width="80%" src="https://user-images.githubusercontent.com/97938271/192174566-d3cedea9-6bb6-4d04-8642-e62fcaf266bc.gif"/>
