### ISSUE TITLE
Questions about graph design and additional features

### ISSUE THREAD

**Issue by parkjisu6239** [Samsung/ONE-vscode#13]
**About Graph Design**

I have a question about visualizing the json file.

By referring to the chrome tracing we are currently using, we are making the screen configuration and design similar.
Using fields such as start time, run time, and so on, and representing them as bar graphs, I think there will be limitations in making them completely new designs.

So the questions I have are as follows.

1. Would it be a problem to make it in a similar form to chrome tracing?
2. From the perspective of real users, among the features of Chrome Tracing, which features would you like to have and which ones you don't really need?
3. What function do you want to add?

**Comment by llFreetimell** [comment]
> 1. Would it be a problem to make it in a similar form to chrome tracing?

I will check this and answer later ASAP

> 2. From the perspective of real users, among the features of Chrome Tracing, which features would you like to have and which ones you don't really need?

Only limited to the features of chrome tracing,

- What we really need
  - Seeing timeline
  - Seeing detailed information for each node
- What we do not need
  - Except above things

> What function do you want to add?

- Seeing timeline of all operations
- Seeing detailed information of each operations
- Seeing detailed circle node which is corresponded to certain operation
- Seeing pie graph for each type of operations

**Comment by parkjisu6239** [comment]
Thank you for your answer. I have an additional question.

`Seeing detailed circle node which is corresponded to certain operation`
-> I don't think I have enough data to provide detailed circle information in the JSON file provided, what should I do? Does the actual data include more circle information? For example, are there functions derived, related node information, etc.?

`Seeing pie graph for each type of operations`
-> Is the `type of operations` you are talking about here **a level** or **a category**? Or is it **something else**?

**Comment by llFreetimell** [comment]
> I don't think I have enough data to provide detailed circle information in the JSON file provided, 

Unfortunately, yes it is :(

> what should I do? Does the actual data include more circle information? For example, are there functions derived, related node information, etc.?

This needs deep consideration because we should read circle file and then get the data.
In ONE, there are already those codes but it is written as C++ and used for the modules in ONE, not ONE-vscode.
Therefore, we should find or write the method for reading circle model :(
One good news is... `netron` has javascript codes to read TFLite file and it may be quite similar with what we want to do...!

---

> Is the type of operations you are talking about here a level or a category? Or is it something else?

Sorry, ignore this one... I thought that it may be useful but after re-thinking, I think it is not that meaningful :(
I will suggest another features!

**Comment by llFreetimell** [comment]
@parkjisu6239 

How about closing this issue?
I think further discussion can be done at #28 :D

**Comment by parkjisu6239** [comment]
Yes, I think there has been sufficient discussion on the content.
Additional discussions will be made on Issue #28 , and the issue will be closed. :)
