### ISSUE TITLE
[Visquv] review and revision

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE-vscode#1386]
Initial version has landed but with not much of thoughts with UI and features.
This issue is to gather usage feedback and add todo actions for better usage.

**Comment by seanshpark** [comment]
CC @jinevening

**Comment by seanshpark** [comment]
TODOs (to be added more)
- [ ] show quantization error value in `NODE PROPERTIES`
- [ ] walk through menu features and remove if not necessary for `Visquv`.
- [ ] ...

**Comment by seanshpark** [comment]
Internal refactoring
- [ ] add quantization error value to `node` property
- [ ] ...

**Comment by seanshpark** [comment]
Show in properties side bar;
![image](https://user-images.githubusercontent.com/4616940/196581639-5d0fb7cb-6fe4-4a23-84ac-b5523bca44b3.png)

@jinevening , I've used `quant-error` field name... do you have any better display name for this?

**Comment by seanshpark** [comment]
Internal bug fixes
- [ ] fix VisqViewer to reflect model path change
- [ ] ...

**Comment by jinevening** [comment]
> @jinevening , I've used quant-error field name... do you have any better display name for this?

Is it possible to use the metric name in the 'meta' section?

**Comment by seanshpark** [comment]
> Is it possible to use the metric name in the 'meta' section?

Ah, yes :)

**Comment by seanshpark** [comment]
done for now...
