### ISSUE TITLE
[ONE-vscode] Toolchain installation issue

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE-vscode#1463]
## What

Toolchain installation fails.

![image](https://user-images.githubusercontent.com/5449554/210680620-375c710e-c90b-4e74-a6bf-52caaf13afc5.png)

I made a vsix package following the guide in https://github.com/Samsung/ONE-vscode/blob/main/docs/HowToBuildFromSource.md.
(commit id: 2131b304c5eeb32f594f06660f8a03ad2d8bdfab)

I installed the vsix in vscode, but toolchain is not installed well.

Could someone help to resolve this issue?

NOTE @seanshpark found that ONE-vscode works well in developer mode. This issue is related to release mode.

**Comment by dayo09** [comment]
Have you installed one-vscode-triv.vsix, too? The guide only gives directions for building the package.
You can install the backend package [here](https://github.sec.samsung.net/RS7-RuntimeNTools/ONE-vscode-TRIV/releases/tag/0.3.0)

**Comment by seanshpark** [comment]
>  works well in developer mode.

This was with running with F5.

>  related to release mode.

This was with running with installed vsix.

> Have you installed one-vscode-triv.vsix, too? T

I think this is the reason :)

**Comment by dayo09** [comment]
I am searching the problematic commit..


0356ea7 [CircleEditor] Revisit editing function (#1458) : NOT WORKING
61abc04 [Utils] Introduce obtainWorkspaceRoots (#1424) : OK
061343d [Toolchain] Do not return undefined type in ToolchainProvider (#1383) : OK
541d569 [OneToolchain] Returns the output value as it is (#1336) : OK

**Comment by jinevening** [comment]
I installed one-vscode-triv.vsix too.

![image](https://user-images.githubusercontent.com/5449554/210720209-963c091a-c87c-42bf-acb4-14b989ce4693.png)

But it still does not work. Toolchain is not installed.

**Comment by dayo09** [comment]
I found out that #1441 caused the problem.


<details>
<summary>
vsce install/uninstall automation script
</summary>

```sh
#!/bin/bash

git checkout $1
vsce package
code --uninstall-extension one-vscode
code --install-extension one-vscode-0.3.0.vsix
```

</details>

**Comment by dayo09** [comment]
I checked that #1464 resolves the error. Thanks for reporting!

**Comment by dayo09** [comment]
It's merged, let me know if there is still a problem :-D

**Comment by jyoungyun** [comment]
However, the toolchain installation will still not be installed. Because the ONE-vscode v0.3.0 uses apt artifactory but this artifactory ended on December 31, 2022. If you want to use ONE-vscode now, you need to build it manually. I will make a PR for this.

**Comment by jinevening** [comment]
> It's merged, let me know if there is still a problem :-D

It works well with the latest commit  :) @dayo09 Thanks for the help!
