### ISSUE TITLE
Introduce manual mixed precision quantization 

### ISSUE THREAD

**Issue by stamalakhov** [Samsung/ONE-vscode#1491]
### What?
Let's implement manual mixed precision feature via editing quantization json file similar to `PartEditor`.

### Why?
Currently setting all values via .json is laborious, so it seems like setting them in GUI will be more convenient.

**Comment by stamalakhov** [comment]
Please correct me if I'm wrong, but
IMHO
the best way to create/edit .json suitable for mixed precision quantization is to create context_menu_item (e.g. `create mixed precision quantization json`) for float `circle` model or (`edit mixed precision quantization json`) for json file.

**Comment by seanshpark** [comment]
> the best way to create/edit .json suitable for mixed precision ...

As I didn't think much on this feature but I can assume you had more on this.
Please share your idea with writing some draft so that others including me can try and think :)

One thing is that one GUI can be nice but can harm harmony with others.

**Comment by stamalakhov** [comment]
> > the best way to create/edit .json suitable for mixed precision ...
> 
> As I didn't think much on this feature but I can assume you had more on this. Please share your idea with writing some draft so that others including me can try and think :)
> 
> One thing is that one GUI can be nice but can harm harmony with others.
> 
> Add: once we have the feature, we can later adjust the entry interface.

Ok. Thank you. I'll be back with a draft.

**Comment by stamalakhov** [comment]
All changes related to MPQ are merged, so it seems that we can close this one.
