### ISSUE TITLE
[CircleGraph] Hierarchical rendering

### ISSUE THREAD

**Issue by stamalakhov** [Samsung/ONE-vscode#1559]
### What
May be we could use some form of hierchical rendering of NN files, when it's possible. 
To show upper-level features of the graph instead of always rendering the nodes of lowest level.
Intead of rendering NN like this:
![image](https://github.com/Samsung/ONE-vscode/assets/112689352/fe464663-611b-4f07-9884-844d5bd3748c)

may be there is a possibility to render it like:
![image](https://github.com/Samsung/ONE-vscode/assets/112689352/4bc19ce5-c7e8-4213-8681-ea507b40eee4)

### Why
To make viewing of large neural networks more convenient.

**Comment by seanshpark** [comment]
If you are thinking of changing `netron` based code, I can't accept that.
I do not want to make rebase to upstream hard.

**Comment by stamalakhov** [comment]
> If you are thinking of changing `netron` based code, I can't accept that. I do not want to make rebase to upstream hard.

ok.
