### ISSUE TITLE
[AHUB] Defects

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE-vscode#1579]
![image](https://github.com/Samsung/ONE-vscode/assets/4616940/f06ed4f2-5d6d-4fe2-8a24-45c070c54c7c)

![image](https://github.com/Samsung/ONE-vscode/assets/4616940/6a58235d-1433-4a57-8c8b-dae148ae4bd5)

**Comment by seanshpark** [comment]
CC @jyoungyun

**Comment by dayo09** [comment]
It is expected to be resolved by #1607

**Comment by dayo09** [comment]
https://analysishub.sec.samsung.net/service/analyses/2260326

![image](https://github.com/Samsung/ONE-vscode/assets/17171963/8795cf90-4e78-40ac-aa19-3326d31b45e6)

Done :-D
