### ISSUE TITLE
Managing CQM scores

### ISSUE THREAD

**Issue by lemmaa** [Samsung/ONE-vscode#1580]
9 major defects were found in latest analysis

- https://analysishub.sec.samsung.net/service/analyses/2158929

**Comment by dayo09** [comment]
@lemmaa I failed to open the page. 😢  It says I need a permission, so I requested it.

**Comment by lemmaa** [comment]
> @lemmaa I failed to open the page. 😢 It says I need a permission, so I requested it.

@dayo09 , it has been processed. Please try again and let me know if you have any problem. :)

**Comment by dayo09** [comment]
@lemmaa It works. Thanks!

**Comment by dayo09** [comment]
https://analysishub.sec.samsung.net/service/v1/analyses/2162409/pdf


|  |  | Classification | Checker | Name | File Path
| --- | --- | --- | --- | --- | --- |
1 | Major | 41881 | Undecided | SONARTS.S1535 | /tmp/source_root/ONE-vscode/src/CircleEditor/CircleEditorDocument.ts:479
2 | Major | 41882 | Undecided | SONARTS.S1535 | /tmp/source_root/ONE-vscode/src/CircleEditor/CircleEditorDocument.ts:536
3 | Major | 41883 | Undecided | SONARTS.S1535 | /tmp/source_root/ONE-vscode/src/MetadataManager/PathToHash.ts:40
4 | Major | 41884 | Undecided | SONARTS.S1535 | /tmp/source_root/ONE-vscode/src/MetadataManager/PathToHash.ts:180
5 | Major | 41885 | Undecided | SONARTS.S1535 | /tmp/source_root/ONE-vscode/src/MetadataManager/PathToHash.ts:190
6 | Major | 49572 | Undecided | SONARTS.S1848 | /tmp/source_root/ONE-vscode/src/Tests/Backend/Compiler.test.ts:24
7 | Major | 49573 | Undecided | SONARTS.S1848 | /tmp/source_root/ONE-vscode/src/Tests/Backend/Executor.test.ts:24
8 | Major | 49574 | Undecided | SONARTS.S1848 | /tmp/source_root/ONE-vscode/src/Tests/Backend/Toolchain.test.ts:25
9 | Major | 49575 | Undecided | SONARTS.S1848 | /tmp/source_root/ONE-vscode/src/Tests/Backend/Toolchain.test.ts:58

**Comment by dayo09** [comment]
### SONAR rule References

- 41881, 41882: https://rules.sonarsource.com/javascript/RSPEC-1535/

**Comment by dayo09** [comment]
### How to run

https://analysishub.sec.samsung.net/service/projects/7485#normal-target 
- Click Analyze with commit ID

**Comment by dayo09** [comment]
It's expected that the number of major defect will be zero if the PRs are merged.

**Comment by dayo09** [comment]
### Defects all solved

[Report Link](https://analysishub.sec.samsung.net/service/analyses/2260326)

![image](https://github.com/Samsung/ONE-vscode/assets/17171963/245b1d84-ea16-4db4-8224-dbd504a2ccd4)


Done :-D
