### ISSUE TITLE
Docker rate limit exceeded for url

### ISSUE THREAD

**Issue by dayo09** [Samsung/ONE-vscode#1598]
After setting the default toolchain as onecc-docker latest,
I clicked the run button on my config file and it fails on `rate limit exceeded for url`.
I thought the image was installed because I got the default toolchain.

1. Do I still need network connection to the url even if I have the toolchain installed?
2. Will it be any way to resolve the problem..? 😭 
```
onecc-docker: error: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/Samsung/ONE/releases/latest
```

**Comment by seanshpark** [comment]
Waiting for a while may resolve this problem.
Reason: lots of Samsung employees access with (range of) same IP to github.com, that sometimes exceeds limit of access. github.com prevents too much access to prevent hacks or such.

**Comment by dayo09** [comment]
Thanks for the information. 😄 

However, I still wonder why it needs installation. Does it install the docker image on the run? 🤔

**Comment by seanshpark** [comment]
> I still wonder why it needs installation. Does it install the docker image on the run?

I think the reason is that you want to do "After setting the default toolchain as onecc-docker latest," that is to run with docker image.

**Comment by jyoungyun** [comment]
To resolve this issue, you need to set GitHub Token in Settings (Settings > User > Extensions > ONE-vscode).
You can find the detail information in #1553.

**Comment by dayo09** [comment]
@jyoungyun Thanks, it's resolved :-D 
I am curious why it requires github token on 'run' not 'installation(setting default toolchain)'..?

**Comment by jyoungyun** [comment]
To resolve this issue, you need to update Dockerfile. In our company network system, this code does not work. Instead, we should use mirror docker image. This code is available on public network without any problems.

**Comment by dayo09** [comment]
Thanks. It worked by replacing the `FROM ubuntu:18.04` line to mirror image name.
