### ISSUE TITLE
[EdgeTPU Backend] Expanding Directions for Steps Following EdgeTPU Import

### ISSUE THREAD

**Issue by imsw0529** [Samsung/ONE-vscode#1623]
### Here is our project introduction

Project Introduction : #1621

### Background

To fully utilize EdgeTPU during inference, the model needs to the following requirements.

- Tensor parameters are quantized(8-bit fixed-point numbers. int8 or unit8)
- Tensor sizes are constant at compile-time(no dynamic sizes)
- Model parameters are constant at compile-time
- Tensors are either 1-, 2-, or 3-dimensional
- ⭐***The model uses only the operations supported by the EdgeTPU⭐***

[[Edge TPU model requirements](https://coral.ai/docs/edgetpu/models-intro/#model-requirements)]

At this time, there is no means to effectively utilize the output compiled with EdgeTPU Compiler. Registering an EdgeTPU device is not feasible, and since the result is configured with `edgetpu-custom-op`, it cannot be converted into the `.circle` format. Consequently, we need to implement a new step specifically for EdgeTPU.

Initially, we've implemented only the import step, but we want to leave a room for expansion, At this point, we are interested in gathering your thoughts on how to present the UI for additional steps(ex. Opimize, Quantize). 

### Our Design

We designed to compile a model that satisfies the Edge TPU model requirements. Accordingly, we do not support the steps after the “import” in the existing configuration editor of ONE-vscode. Therefore, when opening the cfg file for EdgeTPU Compiler in the configuration editor, we plan to just hide the steps following the `import step` to ensure compatibility.

### Expanding Direction

We can support model optimization and quantization by implementing `Optimize Step` and `Quantize Step` in the config editor’s `Step` section. In the `Quantize Step`, users can run quantization for TensorFlow models to satisfy the requirements of EdgeTPU Compiler so that the operations in a model are executed on EdgeTPU as many as possible.

The possible implementation to consider is as follows.

- Providing configuration for Post-training quantization using TensorFlow Lite Converter in the `Quantize Step`.
- The result of `Quantize Step` will be a quantized TensorFlow Lite model more suitable for EdgeTPU.

[[Post-training quantization using TensorFlow Lite Converter](https://www.tensorflow.org/lite/performance/post_training_quantization)]

### Problem

1. As described in the above text, we are planning to implement only `import step`. Accordingly, there is no need to show the steps from the existing cfg file that are not yet implemented (e.g : Optimize, Quantize … etc.). We are curious about your opinion on simply disabling these steps for the expansion.
2. We are currently at the starting point of supporting EdgeTPU. Therefore, we would like to hear the opinions of many people about the direction of expansion. Starting from the import step, we want to proceed with implementation step by step. We appreciate your opinion on this issue.

**Comment by dayo09** [comment]
> 1. As described in the above text, we are planning to implement only import step. Accordingly, there is no need to show the steps from the existing cfg file that are not yet implemented (e.g : Optimize, Quantize … etc.). We are curious about your opinion on simply disabling these steps for the expansion.

Actually, 'import' implies that `onecc` imports a model into `circle`.
I think 'compile' is the better term for running edgetpu compiler on cli.

> 2. We are currently at the starting point of supporting EdgeTPU. Therefore, we would like to hear the opinions of many people about the direction of expansion. Starting from the import step, we want to proceed with implementation step by step. We appreciate your opinion on this issue.

I think we could add 'profile' step in the future, so considering that extensibility is good.

**Comment by dayo09** [comment]
### About the configuration file for edge tpu backend

IMO, it's another way that we separate edge tpu cfg file from onecc cfg file.

It's a design decision. So let's talk about it a while.



#### Scenario
When a user wants to compile a tflite file into either edge-tpu tflite or one circle, the user will select the tflite file and open configuration file on our extension.

If the user is gonna continue with edge tpu compiler, (compile, profile, etc) he/she will never use 'onecc' with the intermediate models. 
Therefore, it's better we provide two different view for each workflow.

#### Expected 'steps' for edge tpu
- compile : compiling from tflite to edge tpu
- profile : profiling a compiled model

#### Choosing file extension
(1) Using the same extension with one cfg
  - In the current onecc cli (a.k.a one-cmd) implementation, it doesn't care about it's unknown sections. So it could be acceptable that we add our ONE-vscode original sections to one cfg file. (It didn't raise error with any arbitrary section inside)
(2) Coming up with a new extension, such as edgecfg or so.



@jyoungyun @lemmaa Here, we are going to discuss on design decisions for edge tpu configuration file. Could you give your opinions, too?

**Comment by dayo09** [comment]
From our offline conversation, we choose to define *.edgetpucfg.

>  (2) Coming up with a new extension, such as edgecfg or so.
