### ISSUE TITLE
Nominating Jiyoung Yun (@jyoungyun) to become a ONE-vscode committer

### ISSUE THREAD

**Issue by jyoungyun** [Samsung/ONE-vscode#1634]
I would like to become a ONE-vscode committer.
I'm a Toolchain View maintainer and the person in charge of ONE-vscode Release.

Meaningful PR list:
https://github.com/Samsung/ONE-vscode/pulls?q=is%3Amerged+is%3Apr+author%3Ajyoungyun+

I promise to merge only PR with more than one other person's approval.

Please give me an opinion. @Samsung/one-vscode, @lemmaa, @seanshpark, @dayo09

**Comment by dayo09** [comment]
:+1:

**Comment by lemmaa** [comment]
@jyoungyun , thank you for your active participation. :)
