### ISSUE TITLE
VSCode and Node version?

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE-vscode#21]
### WHAT
Let's discuss and decide program versions that are related with our task.

### WHY
Working on different version may make confusion.

### ALT
Or is `package.json` file enough?

**Comment by seanshpark** [comment]
This is the initial version made from `yo` tool (#18)

```json
  "devDependencies": {
    "@types/vscode": "^1.46.0",
    "@types/glob": "^7.1.3",
    "@types/mocha": "^8.0.4",
    "@types/node": "^12.11.7",
    "eslint": "^7.15.0",
    "@typescript-eslint/eslint-plugin": "^4.9.0",
    "@typescript-eslint/parser": "^4.9.0",
    "glob": "^7.1.6",
    "mocha": "^8.1.3",
    "typescript": "^4.1.2",
    "vscode-test": "^1.4.1"
  }
```

**Comment by OTKRyu** [comment]
i guess if (#18) pr will be successfully merged, everyone do something based on remote repo.
so i think `package.json` is enough.

**Comment by seanshpark** [comment]
For now, we'll use version as below
- "@types/vscode": "^1.46.0",
- @types/node": "^12.11.7",

Version for these two may change in (near) future by any requirements.
- currently there is no requirement as I know.

**Comment by seanshpark** [comment]
From https://github.com/Samsung/ONE-vscode/pull/195#issuecomment-930769225

> I confirmed with the team that there was nothing wrong with npm7. Perhaps it is because the npm version of the format checker is 6.

> Interesting... the format.patch includes reverting all the changes in this PR @.@ (Except package.json)

> This is script to run check format in CI
```
  check-format:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
```
> node version 12 be the reason?

**Comment by llFreetimell** [comment]
With #202, node-version 16 seems have no problem with our current repository.

If so, my only concern is maintenance of Node.js.
According to https://nodejs.org/ko/about/releases/, following schedule can be checked.

Release | Status | Codename | Initial Release | Active LTS Start | Maintenance LTS Start | End-of-life
-- | -- | -- | -- | -- | -- | --
v12 | Maintenance LTS | Erbium | 2019-04-23 | 2019-10-21 | 2020-11-30 | 2022-04-30
v14 | Active LTS | Fermium | 2020-04-21 | 2020-10-27 | 2021-10-19 | 2023-04-30
v16 | Current |   | 2021-04-20 | 2021-10-26 | 2022-10-18 | 2024-04-30

According to this, LTS version 12 will be ended after 6~7 months and LTS version 16 will be started from next month.
Given this, I think using version 16 in advance for one month seems not that bad :)

**Comment by seanshpark** [comment]
I think we can close this issue. Feel free to reopen for more discussions.
