### ISSUE TITLE
discussion about extracting backend output json file

### ISSUE THREAD

**Issue by yesfordev** [Samsung/ONE-vscode#22]
There is a discussion to extract the contents from the json file that is the backend output and visualize it.

1. Is it visualizing by extracting the contents of the json file by importing the json path from the .cfg file?
2. Is it possible to directly open the json file and extract the contents?

We need to discuss which direction to go in.

**Comment by seanshpark** [comment]
CC @llFreetimell

**Comment by llFreetimell** [comment]
@yesfordev 

If I understand correctly, "visualizing by extracting the contents of the json file by importing the json path from the .cfg file" was what I first thought.

- Get json path from `.cfg`
- read content in json
- Visualize or do something other

But I am still curious what is "directly open the json file and extract the contents" T.T

**Comment by seanshpark** [comment]
> Get json path from .cfg

Just curious... in which part of `.cfg` do we get `JSON` path?

**Comment by llFreetimell** [comment]
@seanshpark 

I am thinking something like picture in https://github.com/Samsung/ONE-vscode/issues/8#issue-976300410.

**Comment by seanshpark** [comment]
> I am thinking something like picture in #8 (comment).

Thanks, `path` gave me some misunderstanding :) 
For me, it seems the file name. `path` = `folder` + `filename` , where we need to ask to system to get the folder...

**Comment by yesfordev** [comment]
When I open a file and run extension, I have the function to read open files in extension. So I was wondering if I should load the contents with the json file open.

But now I know it's from a .cfg file, so I'll do it! :)

**Comment by llFreetimell** [comment]
@yesfordev 

I think we can close this issue :)
For further discussion, they can be handled at #28 !

**Comment by seanshpark** [comment]
Closing as not active. Feel free to reopen if needed.
