### ISSUE TITLE
Questions about codelens

### ISSUE THREAD

**Issue by Seojeonguk** [Samsung/ONE-vscode#243]
I have two questions about codelenses...
1. The current codelens is provided as soon as it starts. This is because the variable(`one-vscode.enableCodelens`) in `package` is true as a default value. Should I maintain the current way? Or should we call the command once and provide it?

2. If the attribute name is the same in each tool, the description is the same. For example, `input_path` or `output_path`...
Currently, if you press the input_path codelens of one-import-onnx, only the input_path in onnx will be hidden. Or should we hide the explanation of input_path in other tools?

**Comment by seanshpark** [comment]
> Should I maintain the current way? Or should we call the command once and provide it?

Is there any strange behaviour as of now?

**Comment by seanshpark** [comment]
> 2. If the attribute name is the same in each tool,  ...

It's a bit hard to understand by explanation... Could you provide how to reproduce this?

**Comment by Seojeonguk** [comment]
> > Should I maintain the current way? Or should we call the command once and provide it?
> 
> Is there any strange behaviour as of now?

There is no problem with its function. 
But the reason why I asked is that other functions are notified(?) of the start through command.

**Comment by Seojeonguk** [comment]
> > 1. If the attribute name is the same in each tool,  ...
> 
> It's a bit hard to understand by explanation... Could you provide how to reproduce this?

![image](https://user-images.githubusercontent.com/44386047/135965716-7614e8b0-9b2d-4ef1-8bbf-7a0e44a50e61.png)
The `input_path` of `tflite` and `input_path` of `bcq` are the same.
Currently, when you press the codelens above the `input_path` of `tflite`, only the codelens for the `input_path` of `tflite` is hidden.
When pressing the codelens for `input_path` of `tflite`, would it be better to hide the codelens for `input_path` of `bcq`?

**Comment by seanshpark** [comment]
> But the reason why I asked is that other functions are notified(?) of the start through command.

Not sure I could provide a right(?) answer, as I'm not experienced develop on this area.
What I could say ask is "how does other codelense behave?" and follow like them.
My personal opinion is (1) current behaviour seems OK and (2) if possible we can provide a method to toggle it (by settings window or by command)

**Comment by seanshpark** [comment]
> When pressing the codelens for input_path of tflite, would it be better to hide the codelens for input_path of bcq?

I think not. 
Why? The argument `input_path` happens to be same and the comment also happens to be same. But as they are different items and swithed(visible and hidden) by diffent position(where it is clicked).

**Comment by Seojeonguk** [comment]
> Not sure I could provide a right(?) answer, as I'm not experienced develop on this area. What I could say ask is "how does other codelense behave?" and follow like them. My personal opinion is (1) current behaviour seems OK and (2) if possible we can provide a method to toggle it (by settings window or by command)

Codelenses are always provided, so I'll keep the current status. Thank you. :)

**Comment by Seojeonguk** [comment]
> I think not. Why? The argument `input_path` happens to be same and the comment also happens to be same. But as they are different items and swithed(visible and hidden) by diffent position(where it is clicked).

Because the description is the same, I thought that if you don't want to see the description of the `input_path` of `tflite`, you might not want to see it either in the `input_path` of `bcq`.

**Comment by seanshpark** [comment]
> I thought that if you don't want to see the description of the ...

I think this is also reasonable...
I think this is kind of user experience and there is no one right answer... 
Follow your heart :)

**Comment by Seojeonguk** [comment]
> But as they are different items and swithed(visible and hidden) by diffent position(where it is clicked).

I think so too. I asked this question because if the line of the cfg file is prolonged, it may be cumbersome to press one by one. 
I will maintain the current situation for two questions. If there is anything cumbersome later, I don't think it'll be too late to change it then.

**Comment by Seojeonguk** [comment]
Thank you for opinion :)
I will close this issue as all the questions have been solved.
