### ISSUE TITLE
`Run Extension` failed

### ISSUE THREAD

**Issue by YongseopKim** [Samsung/ONE-vscode#274]
Hello all. I'm new here. I'm trying building the extension. But, I faced the following error log when I ran `Run Extension` and `Extension Tests`.

My host vscode window poped up the message.
```
The terminal process "C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command npm run watch" terminated with exit code: 1.
```

My debug vscode window poped up the message
```
Activating extension 'undefined_publisher.one-vscode' failed: Cannot find module 'c:\Users\yons.kim\Documents\GitHub\ONE-vscode\out\extension.js' Require stack: - c:\Users\yons.kim\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js - c:\Users\yons.kim\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-amd.js - c:\Users\yons.kim\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js.
```

What did I miss?

**Comment by YongseopKim** [comment]
FYI, on Windows10 and

```
PS C:\Users\yons.kim\Documents\GitHub> npm ls -g
C:\Users\yons.kim\AppData\Roaming\npm
+-- generator-code@1.6.6
`-- yo@4.3.0
```

**Comment by seanshpark** [comment]
Windows native was not considered; ONE doesn't have Windows release.
If you have a Linux machine, please use by connecting through ssh.

**Comment by YongseopKim** [comment]
> Windows native was not considered

Yes, you're right. But I thought it didn't seem to be related to `Windows native`.

Therefore, I tried and I got it. The above error message was printed because of uninstalled modules.
```
ONE-vscode$ npm install 
```
resolves the error.

```
CORP+yons.kim@yons-kim04 MINGW64 ~/Documents/GitHub/ONE-vscode (main)
$ npm run compile

> one-vscode@0.0.1 compile
> tsc -p ./

CORP+yons.kim@yons-kim04 MINGW64 ~/Documents/GitHub/ONE-vscode (main)
$ echo $?
0

```

Anyway, building(not running) `ts` files is successful.
