### ISSUE TITLE
Code changes over multiple modules

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE-vscode#277]
As of now, I've managed to let changes be in one purpose and in modules (sub folders in src folder).
This was to give a chance to authors to verify once more as it can be small and
make a better reviews for the reviewers. And this came from experience of ONE compiler frontend.

Some developers don't like this cause of maybe sending multiple PRs is waste of time and may others I don't know.
I think there are cons and pros about this.

I'd like to gather opinions and discuss about this and decide which way to go.
a) changes should be in 1 project folders and would be better in small amounts
b) multiple projects are OK but should be in one purpose
c) anything is OK
d) ...

**Comment by hyunsik-yoon** [comment]
I prefer b) especially when whole code lines in a PR for one purpose are not very long but the PR has code in multiple sub-projects. 😃

**Comment by jyoungyun** [comment]
> I prefer b) especially when whole code lines in a PR for one purpose are not very long but the PR has code in multiple sub-projects. 😃 

+1 😄

**Comment by llFreetimell** [comment]
+1 for b)

because `media/` and `src/` may be changed at the same time...? (not sure)

**Comment by seanshpark** [comment]
> In this case, what name is to be a headline tag?

I think without headline tag would reduce confusion.
Or,
We may follow https://www.conventionalcommits.org/
- https://sparkbox.com/foundry/semantic_commit_messages

**Comment by dayo09** [comment]
+1 for b)

I've never created PR til now within this repository, so I am not sure.
It seems that multiple changes across directories are required to implement one functionality, by taking a look at some previous prs.
I am a bit worried that we may get a lot of PR conflicts. But we can gather together and reconsider this again, right?

**Comment by YongseopKim** [comment]
+1 for `b) multiple projects are OK but should be in one purpose`

**Comment by seanshpark** [comment]
ok to close
