### ISSUE TITLE
[Visualization] Show profiling json file

### ISSUE THREAD

**Issue by llFreetimell** [Samsung/ONE-vscode#28]
## What?

Let's show following profiling json file in vscode extension.

- [sample2.profile.json.txt](https://github.com/Samsung/ONE-vscode/files/7096080/sample2.profile.json.txt)

#### Example Result

![image](https://user-images.githubusercontent.com/42528189/132146954-9a34c89a-347f-45ba-b4a1-d2de3203d77a.png)

## Candidate Features

- [ ] Register this feature at Command list
- [ ] Get JSON file path from Command Palette
- [ ] Show timeline (with scroll bar)
- [ ] Show `Args` data in JSON
- [ ] Show utilization ratio
- [ ] Zoom in / Zoom out
  - [ ] by button
  - [ ] by scroll
- [ ] Capture
- [ ] Darkmode / Lightmode
- (TBA if needed)

#### Draft

- #52
  - Because of react, whole structure should be refactored

/cc @CODe1995 @yesfordev @parkjisu6239 @donggillee-dev @wnsdud4197

**Comment by parkjisu6239** [comment]
@llFreetimell  

![image](https://user-images.githubusercontent.com/42528189/132146954-9a34c89a-347f-45ba-b4a1-d2de3203d77a.png)

This screen is being developed on the web.
We are going to convert to vscode extension and implement additional features within this week.
