### ISSUE TITLE
[CI] Upgrade node version from 12 to 16

### ISSUE THREAD

**Issue by llFreetimell** [Samsung/ONE-vscode#286]
### What?

Let's upgrade version of `node` from 12 to 16!

### Why?

According to https://nodejs.org/en/about/releases/, EOF of v12 is comming!!

RELEASE | STATUS | CODENAME | INITIAL RELEASE | ACTIVE LTS START | MAINTENANCE LTS START | END-OF-LIFE
-- | -- | -- | -- | -- | -- | --
v12 | Maintenance LTS | Erbium | 2019-04-23 | 2019-10-21 | 2020-11-30 | 2022-04-30
v14 | Maintenance LTS | Fermium | 2020-04-21 | 2020-10-27 | 2021-10-19 | 2023-04-30
v16 | Active LTS | Gallium | 2021-04-20 | 2021-10-26 | 2022-10-18 | 2024-04-30

As current active LTS is v16, let's upgrade with it :)

#### Related PR/Issue

- Background
  - https://github.com/Samsung/ONE-vscode/issues/21#issuecomment-930773333
  - https://github.com/Samsung/ONE-vscode/pull/195#issuecomment-930769225
- Draft
  - #202
- Todo
  - #291

**Comment by hyunsik-yoon** [comment]
draft is not #16 but ##202, isn't it? 😄

**Comment by llFreetimell** [comment]
Done!
