### ISSUE TITLE
Relation between vscode workspace and ONE-vscode

### ISSUE THREAD

**Issue by hyunsik-yoon** [Samsung/ONE-vscode#290]
<sup>------- start of modification on Feb 23 ----------</sup>
I think it's time to draw some UI screen.

VS-code has the following components.
<img src="https://code.visualstudio.com/assets/api/extension-capabilities/extending-workbench/workbench-contribution.png" width=480/>

I think we can start from _Tree View_. (Contents in _Web View_ is depend on contents in _Tree View_.)

Most vscode extensions works in some relation with workspace. Thus, contents on `Tree View` is somewhat related to files in workspace.

So, I think that the relationship between ONE-vscode extension and opened workspace needs to be discussed.

Options of relations could be one of the following:

<sup>------- end of modification on Feb 23 ----------</sup>

1. No relation
    - let's make ONE-vscode work regardless of workspace.
    - similar example: [Remote Explorer extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh) which shows remote hosts in its explorer view, which has no relation with opened workspace.
    - pros
      - compilation is easy. Open vscode and start compiling.
      - developers can select model file and data file in any device (Win or Linux) by importing those files.
        - since data is normally huge, it is highly possible that data files are managed in, e.g., shared file system like NFS or samba, etc.

2. Workspace for TF or PyTorch model development
    - let's make ONE-vscode work on workspace with, e.g., PyTorch model development
    - pros
      - Relation is clear to understand but...
    - cons
      - ONE-vscode provides _little_ (or _no_) functionality for the workspace, which seems to be silly. Developers may ask "why should we open workspace?"
 
3. Make developers create a new workspace
    - let's ask developers to create a workspace containing models such as tflite, onnx, etc.
    - pros
      - It is intuitive to understand the relation between workspace and ONE-vscode.
    - cons
      - vscode provides no function (e.g., editing) on model files. So it is questionable why such workspace should be created in vscode.
      - model files and data files should be stored in a same machine but I am not 100% sure if this is preferred by developers.
      - This option makes developers organize model file and data file under a directory (workspace root). However, developer may have different way of managing their model files.

My preference is:  3) (most preferred) > 1) > 2) (least preferred) because
- option 3) seems good for start
- Maybe later we could combine 3) and 1) if we have requirements for 1).
- option 2) may reduce usage frequency of  ONE-vscode.

Please feel free to suggest your preference. 😸

**Comment by seanshpark** [comment]
@hyunsik-yoon , can you share the problem why you posted this issue? 
for me, I don't know why workspace should be cared or considered for ONE-vscode.

**Comment by hyunsik-yoon** [comment]
@seanshpark, 

The term, workspace, I used is the term in here: https://code.visualstudio.com/docs/editor/workspaces 😸 

- The relation between extension and workspace is related to which will be shown in UI components in vscode.
  - For example, I guess that Tree View could show the following with each options:

option  |   what could be shown in Tree View
----|-----
option 1) | Tree View does not need to show anything specific to workspace
option 2) | It is better to show some info related to TF or PyTorch files
option 3) | It is better to show some info related to tflite or onnx files

  - To decide such UI, I thought that we need to discuss this issue.

<img src="https://code.visualstudio.com/assets/api/extension-capabilities/extending-workbench/workbench-contribution.png"/>

- The relation with workspace and extension could make an impact on implementation. For example,
  - extension can be installed remotely when workspace files are at remote machine: https://code.visualstudio.com/api/advanced-topics/remote-extensions
  - data can be stored inside workspace storage or global storage: https://code.visualstudio.com/api/extension-capabilities/common-capabilities#data-storage

**Comment by seanshpark** [comment]
@hyunsik-yoon , thanks for the explanation. The `workspace` is same as I thought.
But I can't catch the "PROBLEM" what you want to solve. 
You explained about the options but not the problem. 

What I want to say is if there are some options, that seems to be good, then is would be better to show that option.
Here, I don't see the "PROBLEM".
If showing the option is not in a proper situation, and we can't detect or control the visibility, then this is a "PROBLEM".

**Comment by hyunsik-yoon** [comment]
@seanshpark, I see. I modified https://github.com/Samsung/ONE-vscode/issues/290#issue-1145536517 to show the intention of this posting. Thanks for pointing that out.

**Comment by hyunsik-yoon** [comment]
We decided to use workspace where end-user puts model files.
Let me close this.
