### ISSUE TITLE
[UX/Compile] Organize the compile steps and each step's options

### ISSUE THREAD

**Issue by YongseopKim** [Samsung/ONE-vscode#303]
Parent issue: #300 

Let's organize the compile steps and each step's options.
- Organize Compile steps in ONE-vscode like `import -> optimize -> ...`
- Organize each step's compile options
  - Circle2Circle, CircleOptimizer, One-click compilation, ...
  - Decide optimized option: Opt On/Off or o0/o1/o2 or, ...
- Store these compile options of a model as a config so that users could compile with the config on each different env anytime everywhere

/cc @Samsung/one-vscode

**Comment by hyunsik-yoon** [comment]
related issue : https://github.com/Samsung/ONE/issues/8570
For ONERT, which can handles many backends such as CPU, GPU, NPU, etc., `partitioning` is planned to added later to partition one circle model into sub-circle models for CPU, GPU, NPU, respectively.

**Comment by YongseopKim** [comment]
First, we need to
- [ ] organize(order) compile steps sequentially in ONE-vscode
- [ ] make a list for each step's compile option
- [ ] make a decision on how to separate options - 1) opt on/off 2) o0/o1/o2 3) ...
- [ ] make a decision on how to store compile options to be set on each compile step to each config file

**Comment by YongseopKim** [comment]
## organize(order) compile steps sequentially in ONE-vscode

compile step can be defined as the following steps
1. optimize: uses one-optimize which is relative to circle2circle and CircleOptimizer
2. quantize: uses one-quantize which is relative to circle-quantizer and CircleOptimizer
3. codegen: uses one-codegen which is relative to a backend for something like npu

**Comment by YongseopKim** [comment]
## make a decision on how to separate options - 1) opt on/off 2) o0/o1/o2 3) ...

we will support the default options for each backend.
- the default options to be supported will be being optimized maximally.
- and other options will be supported by advanced options that could be choosen by users.

**Comment by YongseopKim** [comment]
## make a decision on how to store compile options to be set on each compile step to each config file

the options that are chosen by users can be exported to cfg file.

**Comment by YongseopKim** [comment]
Done to organize.
