### ISSUE TITLE
Use `onecc` instead of `one-cmd`

### ISSUE THREAD

**Issue by YongseopKim** [Samsung/ONE-vscode#318]
Current ext uses `one-cmd` like `one-codegen`. These would be changed by `onecc`.

**Comment by YongseopKim** [comment]
As-is
```ts
// Ex) JobCodegen
// `one-codegen arg0 arg1`
// `one-codegen`: tool
// `arg0 arg1`: toolArgs
export interface Job {
  jobType: Job.Type;
  name: string;
  valid: boolean;
  tool: string;
  toolArgs: ToolArgs;
}
```

To-be
```ts
// `Job`s should be used by `onecc`
// Ex) JobCodegen
// `onecc codegen arg0 arg1`
// `onecc`: driver
// `codegen`: command
// `arg0 arg1`: args
export interface Job {
  jobType: Job.Type;
  name: string;
  valid: boolean;
  driver: string;
  command: string; // or just keep using `tool`
  args: ToolArgs; // or CmdArgs
}
```

Anyone can share their own idea. /cc @Samsung/one-vscode

**Comment by YongseopKim** [comment]
I decide to keep it as-is but `onecc` internally runs. See https://github.com/Samsung/ONE-vscode/pull/404.

**Comment by mhs4670go** [comment]
@YongseopKim It would be more helpful if you let us know why we should use `onecc` instead of `one-cmds`.

**Comment by YongseopKim** [comment]
`onecc` is a driver for one-commands. The tool is an entry point for ONE lib. ONE-vscode ext is a role of using ONE in vscode. We need to integrate the entry point.

Therefore, this will be changed like below.
- as-is (now)
  - by cli: `onecc -> one-cmd -> ...`
  - by one-vscode: `one-cmd -> ...`
- to-be
  - by cli & one-vscode: `onecc -> one-cmd -> ...`
