### ISSUE TITLE
Prepare HTML/CSS Template

### ISSUE THREAD

**Issue by hyunsik-yoon** [Samsung/ONE-vscode#331]
Let's prepare html and css template file.

@Samsung/one-vscode team is not familiar with HTML/CSS and having a template page will help the team.
With this template resource, I hope that other sub-teams would create their web pages in more easier way.

- [x] Design UI/GUI for a specific screen(e.g., compilation screen)
- [ ] Add the screen resource as template

**Comment by hyunsik-yoon** [comment]
Compilation : basic 

![image](https://user-images.githubusercontent.com/63768207/158944648-3d6be21b-c13f-466c-81bc-67f8313ce6ad.png)

**Comment by hyunsik-yoon** [comment]
I found this: https://code.visualstudio.com/blogs/2021/10/11/webview-ui-toolkit

**Comment by hyunsik-yoon** [comment]
working code in draft #297 

![image](https://user-images.githubusercontent.com/63768207/159473810-0c70e55b-d612-4a23-8304-09e8ef65bbb5.png)

I will extract css now.

**Comment by hyunsik-yoon** [comment]
Now #297 has a separate css file.

Time to push PR.

**Comment by hyunsik-yoon** [comment]
UI Animated GIF: [one-vscode.zip](https://github.com/Samsung/ONE-vscode/files/8348851/one-vscode.zip)

**Comment by hyunsik-yoon** [comment]
Let me move to the next milestone and finish submitting PRs.

**Comment by hyunsik-yoon** [comment]
I'd like to share an experience while adding [compile] menu when a file (e.g., tflite) or dir (e.g., saved model) was right-clicked.

My dev environment comprises of vscode on **Windows** and workspace on remote **Ubuntu**.

With my draft with #419 and #422, what I wanted to implement in a draft was to see the possibility of those cases:

1. To enable [Compile] context menu when a file with some extensions (e.g. *.tflite, *.onnx, etc)  is right-clicked
2. Search directories containing saved model or Keras model and put them into some list. Then enable [Compile] contextual menu when one of those directories is right-clicked

For 2. I expected the following vscode context with, e.g., `/tmp/saved_model` directory.
- `resourcePath` === `'/tmp/saved_model'`

However, I found the following in [_Developer Tool_](https://code.visualstudio.com/api/references/when-clause-contexts#inspect-context-keys-utility).
- `resourcePath` === `'\\tmp\\saved_model'`

The path looked like a Ubuntu path but the format was Windows format.
So, the following in draft worked:

```ts
  let dirList: string[] = [ '\\tmp\\saved_model' ];
  vscode.commands.executeCommand('setContext', 'onevscode.compilableDirList', dirList);
```

I think that the following cases should be checked to fully implement [Compile] menu on a directory just in case:

- case A) When vscode on Windows uses workspace on Linux,
  - This was `\\tmp\\saved_model`
- case B) When vscode on Linux uses workspace on Linux,
  - This could be probably `/tmp/saved_model`, but not checked yet.
- case C) Workspace is in Linux (no remote environment)
  - This could be probably `/tmp/saved_model`, but not checked yet.
- case D) Workspace is in Windows (no remote environment)
  - This could be probably something like `c:\\tmp\\saved_model`, but not checked yet.

**Comment by YongseopKim** [comment]
>   let dirList: string[] = [ '\\tmp\\saved_model' ];

```ts
dirList = path.join('tmp', 'saved_model');
```

Is it impossible?

**Comment by hyunsik-yoon** [comment]
@YongseopKim 

I ran `dirList = path.join('tmp', 'saved_model');` and `disList` contained `tmp/saved_model`, which was unfortunately **not** what we wanted. 😿

**Comment by YongseopKim** [comment]
Hmm... my one idea. `resourcePath.split(path.sep)` and then compare `['tmp', 'saved_model']`.

**Comment by hyunsik-yoon** [comment]
All required PR's been pushed. Let me close this.
