### ISSUE TITLE
[infra] `format` supports json

### ISSUE THREAD

**Issue by YongseopKim** [Samsung/ONE-vscode#359]
Let's support json on `format` in `infra`.

**Comment by YongseopKim** [comment]
FYI, when I tried it,

```bash
  # Check .ts files
  FILES_TO_CHECK_TS=()
  for f in ${FILES_TO_CHECK[@]}; do
    # File extension to check
    if [[ ${f} == +(*.ts) ]]; then
      FILES_TO_CHECK_TS+=("${f}")
    fi
    if [[ ${f} == +(*.js) ]]; then
      FILES_TO_CHECK_TS+=("${f}")
    fi
  done
    if [[ ${f} == +(*.json) ]]; then
      FILES_TO_CHECK_TS+=("${f}")
    fi
  done
```

I got
```
~/Works/ONE-vscode(draft/mocha ✔) bash infra/format

[WARNING] Commit all the changes before running format check
          format.patch file will contain unstaged files
Configuration file(s) do(es) not support C++: /home/dragon/Works/ONE-vscode/.clang-format
Configuration file(s) do(es) not support C++: /home/dragon/Works/ONE-vscode/.clang-format
Configuration file(s) do(es) not support C++: /home/dragon/Works/ONE-vscode/.clang-format
Configuration file(s) do(es) not support C++: /home/dragon/Works/ONE-vscode/.clang-format
[FAILED] Format checker failed and update code to follow convention.
         You can find changes in format.patch
[[FAILED] Invalid format checker exit.
```

**Comment by jyoungyun** [comment]
When I check the our clang format version, we use `clang-format` version 8. This version does not support `json` file. 
https://releases.llvm.org/8.0.0/tools/clang/docs/ClangFormat.html

That's the reason why it is failed.

latest clang format is v15. And I will check the possibility of using the latest version.

**Comment by llFreetimell** [comment]
```
Configuration file(s) do(es) not support C++: ONE-vscode/.clang-format
```

This error is becuase `Language: Javascript` in `.clang-format` cannot support JSON.
If we fix the file as following, it would works
```
Language: JavaScript
BasedOnStyle: Google
ColumnLimit: 100
NamespaceIndentation: None
---
Language: Json
BasedOnStyle: Google
```

However, as @jyoungyun said, JSON is supported from clang-format 13.0.0, which is not supported at Ubuntu-18.04 :(

**Comment by jyoungyun** [comment]
`clang-format` ver 3.9 support to `json` file. And I found a hint to consider the `clang-format-3.9` version.
https://github.com/Samsung/ONE-vscode/blob/e4927521753d10bdcebb9619e4a4044e025de724/infra/format#L21

**Comment by jyoungyun** [comment]
Um, we can use Ubuntu 20.04 on GitHub Action, but the latest version of `clang-format` on Focal is version 10.0. :(

**Comment by YongseopKim** [comment]
In conclusion, json cannot be supported for a while. In the future, if possible, let's support it.

**Comment by jyoungyun** [comment]
Related PR: #361 

If we use Ubuntu 22.04, we can support to format-checker on Json files.
GitHub Actions is not officially support to Ubuntu 22.04 yet.
Self-hosted Runner can be a solution but it costs for maintenance.

**Comment by dayo09** [comment]
If clang-format is not our option, we can use jq or jsonlint instead.

**Comment by hyunsik-yoon** [comment]
@dayo09 is trying jq at draft #398.
How about going with jq?

**Comment by YongseopKim** [comment]
`jq` looks good. Can `jq` have own config file for setting format?

Like
```
$ cat .clang-format
BasedOnStyle: Google
Language: JavaScript
ColumnLimit: 100
NamespaceIndentation: None
```

**Comment by dayo09** [comment]
> jq looks good. Can jq have own config file for setting format?

No, I don't think it has one.
