### ISSUE TITLE
Process for reading .circle file with typescript

### ISSUE THREAD

**Issue by CODe1995** [Samsung/ONE-vscode#36]
Compile the corresponding [circle_schema](https://github.com/Samsung/ONE/blob/master/nnpackage/schema/circle_schema.fbs) file.
1. Download the executable file appropriate for your OS from [FlatBuffers release 2.0.0](https://github.com/google/flatbuffers/releases).
2. It can be compiled into various languages ​​as shown in the picture below.
![image](https://user-images.githubusercontent.com/47562093/132163787-30561b3d-65fa-4f42-b88c-6c965709234f.png)
3. Enter the following command:
    ``` flatc --ts -o ./{path to save} ./schema.fbs ```
4. You can see the compiled result in the specified path.
5. Now we need to find a way to read the circle file with this compiled output.

/cc @yesfordev @parkjisu6239 @donggillee-dev @wnsdud4197

**Comment by donggillee-dev** [comment]
Thank you for your explanation👍

**Comment by yesfordev** [comment]
Thank u!! :)
but now it seems that javascript is not supported. T.T

**Comment by llFreetimell** [comment]
In https://google.github.io/flatbuffers/flatbuffers_guide_use_javascript.html, following announcement is found :(

```
Due to the complexity related with large amounts of JS flavors and module types, native JS support has been replaced in 2.0 by transpilation from TypeScript.

Please look at TypeScript usage and transpile your sources to desired JS flavor. The minimal steps to get up and running with JS are:

Generate TS files from *.fbs by using the --ts option.
Transpile resulting TS files to desired JS flavor using tsc (see https://www.typescriptlang.org/download for installation instructions).
```

**Comment by mhs4670go** [comment]
Could you let me know about the information you want to read?

**Comment by CODe1995** [comment]
@yesfordev 
There is a way but it looks complicated
[transpile into javascript](https://code.visualstudio.com/docs/typescript/typescript-compiling#_transpile-typescript-into-javascript)

**Comment by seanshpark** [comment]
> There is a way but it looks complicated
transpile into javascript

This repo is(will be) developed with TypeScript...

**Comment by yesfordev** [comment]
> Could you let me know about the information you want to read?

We need to check circle file information using circle_schema. I am trying to check circle_schema by converting it to javascript or typescript by using flatbuffers! :)

**Comment by seanshpark** [comment]
> We need to check circle file information

Another way is to develop npm native module library in ONE and use it here... somehow...
- This is a view point of execution time of flatbuffer validation time taken in JS engine
- If this takes too long with JS (or TypeScript) for typical .circle file, several MB to several 10 MB, it is not good environment to work on.

**Comment by llFreetimell** [comment]
@CODe1995 

Result FLATBUFFER 2.0 seems to be quite different with FLATBUFFER 1.xx -_-
In FLATBUFFER 1.10, `.ts` is also generated as only one file.
