### ISSUE TITLE
Sync with ONE repo circle_schema.fbs

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE-vscode#37]
We need to sync with ONE repo circle_schema.fbs file within this project.
I don't think it is critical with versions changes

Background what this can be an issue
- circle_schema may have to follow new tflite format, as we need to upgrade to latest TF version
- new TF may drop new format tflite file which our `tflite2circle` may crash; I've seen this one with some models

**Comment by seanshpark** [comment]
From  #36

**Comment by seanshpark** [comment]
Just thinking how to...
- add ONE as git sub module
- download `circle_schema.fbs` at build time(?)
- make a copy of `circle_schema.fbs` to this repo
- ...

**Comment by llFreetimell** [comment]
- Just add `circle_schema_generated.ts` (or .js)
  - `circle_schema.fbs` will not be changed frequently
  - ONE Runtime and netron are already using this approach
  - Whenever we try to compile `.fbs`, it would take much time to compile and load.

**Comment by seanshpark** [comment]
closing as it's old.
