### ISSUE TITLE
Using ssh-cli vs ssh-extension

### ISSUE THREAD

**Issue by dayo09** [Samsung/ONE-vscode#391]
### Design
Discussed design so far is,

- Local Machine --(transfer file/command via ssh/sdb connection, not ssh extension)--> Remote Machine (Ubuntu/Tizen)
- Run docker on ubuntu machine, execute inside the docker <- `by ssh cli command only`
- pull out result(model, benchmark result, log, ...) to local machine with docker

### UI
UI is not discussed in a group yet. 
This includes my suggestions.

#### ssh connection
Present the similar interface as Remote-ssh extension of vscode. Anyhow, we need the ssh connecting interface too. Let's use the most familiar one.

![image](https://user-images.githubusercontent.com/17171963/159197858-3a400807-2c40-43da-ab67-c665211a4a0e.png)
![image](https://user-images.githubusercontent.com/17171963/159197862-0520a35d-a59c-4eab-9617-66bfb268e786.png)
(source: https://code.visualstudio.com/blogs/2019/07/25/remote-ssh)

#### Q. why don't we just use remote-ssh extension here, not a pure ssh cli command.
I guess  'ssh cli command instead remote-ssh extension' design is suggested as we need to support the same functionals for both ubuntu and tizen board(real env). However, why don't we just separate them and support linux with much extensive view.

_Originally posted by @dayo09 in https://github.com/Samsung/ONE-vscode/issues/343#issuecomment-1073417960_

-----

@dayo09 
I'd like to try to elaborate the reason we decide to **go with ssh cli** (rather than SSH extension).

IMHO, we have to consider two cases with toolchain installed in remote machine.
c1) model files are stored in local Windows machine.
c2) model files are stored in remote machine.

Thinking about c1) 
Assuming a user maintains his/her model file in his/her Windows machine and connects a target device(e.g., TV) to the Windows machine.

In such case, if we choose to support SSH-extension, user has to do
1) open a new vscode by pressing green area (![image](https://user-images.githubusercontent.com/63768207/159404807-4eb595b6-e4f4-47c1-97df-17bd43bd5b9c.png))
2) manually connect remote server through SSH (by entering, e.g., IP)
3) but he/she wants to run a compiled code in _local_ PC. (_this experience seems weird_)
4) compilation on remote machine: ONE-vscode transfers the compiled code to remote machine where toolchain is installed. Toolchain sends the result back to ONE-vscode. Here, we have some mechanisms of passing files and receiving result. (which can be done by ssh cli or scp)
5) inference on target device: ONE-vscode transfers the compiled code to target device, which is connected to _local_ machine. (This is done by, ssh cli or SDB)

In the above scenario, if we choose to use ssh cli, we don't need step 1), 2), making UI steps simpler. Plus, step 3) can be more intuitive. 

c2) can be also done with ssh cli.

_Originally posted by @hyunsik-yoon in https://github.com/Samsung/ONE-vscode/issues/343#issuecomment-1073499411_

-----

@hyunsik-yoon

To tell you my opinion, my main points are,

Point 1. keeping ssh/sdb connection is mandatory in any cases (using ssh-extension or not). Your 4. 5. steps can be done within ubuntu device too.

Point 2.

> 1. open a new vscode by pressing green area (image)
> 2. manually connect remote server through SSH (by entering, e.g., IP)

Those steps cannot be disappeared. When we try to connect to remote machine, we will show up ssh connection UI, which we haven't discussed yet but which I expect to be as similar to the vscode-extension's one.

_Originally posted by @dayo09 in https://github.com/Samsung/ONE-vscode/issues/343#issuecomment-1074705106_

Related to
https://github.com/Samsung/ONE-vscode/issues/310
https://github.com/Samsung/ONE-vscode/issues/343#issuecomment-1073499411

**Comment by hyunsik-yoon** [comment]
How about discussing this in daily meeting at Thu? :-)

**Comment by dayo09** [comment]
Our discussion has concluded to..

This case is using remote ubuntu machine and its workspace.
Therefore, it's just as the same as the case of using local ubuntu machine and its workspace. The only difference is to connect via ssh extension or not.
So we conclude this to use ssh-extension.
