### ISSUE TITLE
The number of PR reviewers

### ISSUE THREAD

**Issue by mhs4670go** [Samsung/ONE-vscode#392]
## What

Let's make a pull request `Labels` named `approvals`.

## Why

Our rule is to have at least 2 reviews for each PR. But some PRs, such as typo corrections, require only one review, which will improve the development process.

## stretch

Labeling could be automated via CI. It would be a way to scan the words in the title or measure the amount of PR.

**Comment by hyunsik-yoon** [comment]
Good opinion. I agree.
Do you propose to make label, like, `1 approval` or `2 approvals` ?

**Comment by mhs4670go** [comment]
@hyunsik-yoon Yes. I'm gonna introduce the labels and let's see if it is good to use:)

**Comment by YongseopKim** [comment]
I also agree! 👍

**Comment by llFreetimell** [comment]
We should change the repository setting..!
For now, if there are no 2 approvals, PR cannot be merged T.T

**Comment by dayo09** [comment]
I agree. I just put up a format-changing PR which is actually in no need of 2 approvals.

**Comment by lemmaa** [comment]
https://github.com/Samsung/ONE-vscode/issues/392#issuecomment-1074924126
> Do you propose to make label, like, 1 approval or 2 approvals ?

It seems like a good idea to try. I will change the repo configuration for it.
