### ISSUE TITLE
[UI] Design UI for Execution Device

### ISSUE THREAD

**Issue by struss** [Samsung/ONE-vscode#394]
Let's think about UI for execution Env.

- [ ] Create Tab below on model Tab

any Idea welcome for this!

WIP

**Comment by struss** [comment]
Currently, my Idea is image on below

![UI_Execute](https://user-images.githubusercontent.com/2858751/159449257-66a71f95-0979-4d66-bd46-03438b00934a.png)

**Comment by hyunsik-yoon** [comment]
I have some questions with this UI.

I wonder what will be the `execution device`. I tried to write down the possible ones....

a) target devices (e.g., TV) that are connected to _local_ PC
b) target devices that are connected to _remote_ PC
c) a docker image that has, e.g., simulator, in _local_ PC  (there could be multiple containers in a PC)
d) a docker image that has, e.g., simulator, in _remote_ PC  (there could be multiple containers in a PC)
e) an executable (not in a container), e.g., simulator or runtime, in _local_ PC
  - depending on simulator, there could be only one in a machine or many in a machine
    - e.g., nnpackage-run is an executable for ONERT and multiple versions can be installed in a PC

e) an executable (not in a container), e.g., simulator or runtime, in _remote_ PC
g) ...

I wonder which of the above are covered with this UI. 

I think some of the above are not covered with this UI. For example, for a), IMHO Tizen TV can be accessed with sdb. Do we need to enter IP? For c), does user need to enter IP? For d), if the remote PC has 5 images, are all 5 images be added into the execution environment?
I am not sure if b) could be one of our target env or not. 😹

**Comment by struss** [comment]
first, those are just my Idea for this, not exact confirm.

In my opinion, `a)` case can be covered `b)` case with localhost IP(127.0.0.1) case.
and `c)` case could be covered with docker with option -p 22:<other_port> to expose.

**Comment by hyunsik-yoon** [comment]
@struss IMHO, entering localhost IP or port seems to provide unusual experience to end-user. I will also think about this.
Also, assuming that installation file contains "compiling env + execution env",
pressing "+" icon on "compiling env" will also install execution env, and pressing "+" icon on "execution env" will also install compiling env. User might be confused about this and we have to provide them not to be confused.

**Comment by dayo09** [comment]
> Also, assuming that installation file contains "compiling env + execution env",
pressing "+" icon on "compiling env" will also install execution env, and pressing "+" icon on "execution env" will also install compiling env.

@hyunsik-yoon 

Have it been discussed offline..?
If not, IMO, I may add an idea : we could just add an 'env' and use them as either of 'compile env' or 'execution env' later on. Anyways on our ONE-vscode policy, the main workspace will be the local.

**Comment by hyunsik-yoon** [comment]
@dayo09 ,
Current UI document has the UI flow for compile env and execution env. :-)

> let's allow users to add env and declare its purpose later on (by installing related tools or so)

I am not sure if I understand this correctly. Could you explain more about this?

/cc @jyoungyun

**Comment by jyoungyun** [comment]
This issue is related to #461 issue.
I will add a view for Executor in this sprint period.

The name of executor view will be `Executor` or `Executor Toolchain` in consistency of `Compiler Toolchain`. What do you think about it?

**Comment by hyunsik-yoon** [comment]
In case of target device, `toolchain` sound weird. For this reason, I prefer `Executor`.
/cc @Samsung/one-vscode

**Comment by dayo09** [comment]
@hyunsik-yoon @jyoungyun I have checked the lastest UI document and it looks very fine. 😄

**Comment by struss** [comment]
As this one added and need more  feature about this, I will close and make a new issue about this.
