### ISSUE TITLE
Introducing `Sudden` label

### ISSUE THREAD

**Issue by hyunsik-yoon** [Samsung/ONE-vscode#402]
During a sprint where some issues were scheduled, sometimes unplanned work happens.
Some work can be simply put into backlog, but some need to start within the sprint.

When unplanned work need to start during the sprint, it could make impact on other scheduled works.
Let's mark the unplanned work with special label, 'sudden'.

Later we can check if our sprint is going well considering works labeled with 'sudden'.

**Comment by YongseopKim** [comment]
IHMO, I'm not good at English so I have a question; `unexpected task` looks better `sudden task` because... `sudden` makes me think of a military operation like `sudden attack.`

**Comment by hyunsik-yoon** [comment]
There are the examples in [Cambridge dictionary](https://dictionary.cambridge.org/dictionary/english/sudden):
- I'd [strongly](https://dictionary.cambridge.org/dictionary/english/strongly) [advise](https://dictionary.cambridge.org/dictionary/english/advise) against making a sudden [decision](https://dictionary.cambridge.org/dictionary/english/decision).
- Everyone in the [office](https://dictionary.cambridge.org/dictionary/english/office) was [surprised](https://dictionary.cambridge.org/dictionary/english/surprised) by Graham's sudden [departure](https://dictionary.cambridge.org/dictionary/english/departure).
- There was a sudden [loud](https://dictionary.cambridge.org/dictionary/english/loud) [noise](https://dictionary.cambridge.org/dictionary/english/noise).

`Sudden` has nuance of "갑자기 치고 들어오는" in Korean. 
I was also thinking about `unexpected`, `unplanned`, or `unscheduled`... but once I starts such work, they are now scheduled and planned. So I thought that it could confuse people.
Plus, `sudden` sounds a bit funnier. :-)

**Comment by YongseopKim** [comment]
@hyunsik-yoon I got it. Thanks! 👍

**Comment by hyunsik-yoon** [comment]
Let me close this. :-)
