### ISSUE TITLE
Implementation of  Installation of Compiling Env & Execution Env

### ISSUE THREAD

**Issue by hyunsik-yoon** [Samsung/ONE-vscode#414]
Let's work on compiling env & execution env.
In this issue, only "local installation of debian package" will be handled.

- [ ] designing UI for compiling env 
- [ ] designing UI for execution env
- [ ] implementation of compiling env
- [ ] implementation of execution env
- [ ] implementation of auto detect (finding if any existing local env already exists)
  - find out the following
    - [ ] are they working 
- [ ] implementation of uninstall
- [ ] implementation of install
- [ ] implementation of install over existing one

Out of scope

- remote installation
- docker installation
- supporting various backends
  - make it for existing backend first
  - consider various backends for easier refactoring later
  - but find clues for various backend support

**Comment by YongseopKim** [comment]
`compiling env / execution env` are very important concepts, I think. And I'm interested in them. Could you share your concrete concepts for impl them?

**Comment by jyoungyun** [comment]
Related issue: #306

**Comment by hyunsik-yoon** [comment]
This issue was **not done**.

I think it's better to close this and reschedule after discussing with @jyoungyun.
