### ISSUE TITLE
A function that helps you understand the functions of tools and options in .cfg file.

### ISSUE THREAD

**Issue by emost22** [Samsung/ONE-vscode#43]
## What
A function that helps you understand the functions of tools and options in .cfg file.
## Why
It is difficult to easily understand the functions of many tools and options when writing .cfg files.
## How
Use codelens to describe the functions of tools and options.

Here's an example of a function.

![image](https://user-images.githubusercontent.com/60142959/132273939-042ff917-26a7-4022-b467-98b336eb2496.png)
This is a sample of codelens and description of tools.

![image](https://user-images.githubusercontent.com/60142959/132274928-caa9d472-5325-4bca-9416-c0e42516a70a.png)
If you place the mouse on this comment, you will find the required options.

![image](https://user-images.githubusercontent.com/60142959/132275166-d04e21fb-ee95-4573-a797-f04e9522419f.png)
If you click on this comment, a message will be output.

**Comment by seanshpark** [comment]
It's a bit hard to understand where this issue came from.
- It would help if you add a link if there is another related issue
- I can imagine your difficulties but that can bring errors in communication

At least
- We don't have any UI in our code so it's hard to catch what or how your capture came from.

**Comment by emost22** [comment]
Codelens is a function provided by vscode.

Here's the url of example.
https://github.com/microsoft/vscode-extension-samples/tree/main/codelens-sample
And some guide.
https://code.visualstudio.com/blogs/2017/02/12/code-lens-roundup

**Comment by seanshpark** [comment]
@emost22 , if I understand correctly, you are working on an text editor for `.cfg` file that shows helper balloons (codelens) ?

**Comment by emost22** [comment]
I don't know understood correctly "text editor" in your question, but I'm working on VSCode.

**Comment by seanshpark** [comment]
> you are working on an text editor for

The text editor window inside VS code...

**Comment by emost22** [comment]
That's right. May I develop for this issue?

**Comment by seanshpark** [comment]
> May I develop for this issue?

I think you are already on this :)
Or I didn't quite understand your question?

**Comment by emost22** [comment]
No, I think you understand :D
Thank you!

**Comment by seanshpark** [comment]
Closing as not active. Feel free to reopen if needed.
