### ISSUE TITLE
Questions about properties when creating cfg files

### ISSUE THREAD

**Issue by Seojeonguk** [Samsung/ONE-vscode#44]
We would like to provide automatic completion function when creating cfg file to users who do not use GUI.
We think it's better to list essential and frequently used properties than to list all properties.

![image](https://user-images.githubusercontent.com/44386047/132276150-85ef8866-7f71-4a1e-9e7b-537ed10d4fad.png)
1. Is it correct that tools other than one-codegen only have input_path and output_path as required attributes and one-codegen only has backend as required attributes?
2. What are the properties that users often use for each tool?

**Comment by seanshpark** [comment]
Q) it's a bit hard to understand `automatic completion function` is... can you provide a link, maybe an example or guide that can hlep me understand it?

**Comment by Seojeonguk** [comment]
vscode provides a feature called snippets.
Link to User Guide. 
https://code.visualstudio.com/docs/editor/userdefinedsnippets

**Comment by seanshpark** [comment]
So you mean, using `automatic completion function` assumes
- user will use text editor to type with, to add or change options or what ever...

Another option what I thought was to use ComboBox (or HTML SELECT element)
But I didn't think about the full UI...

**Comment by Seojeonguk** [comment]
That's right. We're also developing GUI. However, I suggested it for users who want to maintain the traditional approach.

**Comment by Seojeonguk** [comment]
I was able to get the answer through the `-h` attribute of each tool.
