### ISSUE TITLE
Complete to setup internal test infra

### ISSUE THREAD

**Issue by YongseopKim** [Samsung/ONE-vscode#440]
Let's build internal infra to test internal tools.

**Comment by YongseopKim** [comment]
This task should be discussed on the internal github.

**Comment by YongseopKim** [comment]
@hyunsik-yoon so, can you share the current status?

**Comment by hyunsik-yoon** [comment]
I haven't start any activity yet.

I guess that the following tasks are needed to be done.

1. Enabling unit-test for functions which are implemented in ONE-vscode and have dependency with backend toolchain
  - e.g., ` mocha = new Mocha({ui: 'tdd', color: true, fgrep: '@Use-onecc'})` 
2. Calling unit-test for functions which are implemented in backend repo that requires installation of ONE-vscode

**Comment by hyunsik-yoon** [comment]
Please start anything if you'd like to start implementing this issue. 😸

**Comment by hyunsik-yoon** [comment]
Can I think about how 2 can be done? 😸

**Comment by YongseopKim** [comment]
About No.1 task

> Enabling unit-test for functions which are implemented in ONE-vscode and have dependency with backend toolchain
e.g., mocha = new Mocha({ui: 'tdd', color: true, fgrep: '@Use-onecc'})

To do it,
1. fgrep option should be passed on like env options and then run it
2. and we could use just `git clone ONE-vscode`

**Comment by hyunsik-yoon** [comment]
I will explore how to test 2 in internal repo.

**Comment by hyunsik-yoon** [comment]
I guess this work has been done. We have test infra running in public repo as well as SEC repo.
