### ISSUE TITLE
which location is better for created configuration file(#10)?

### ISSUE THREAD

**Issue by OTKRyu** [Samsung/ONE-vscode#45]
currently, i try to make webview vscode extension(https://github.com/Samsung/ONE-vscode/issues/10) for making configuration file for ONE.
but i can't decide which location is better for created configuration file.
now, i think that user can choose location of configuration file is the best, but i think default setting is necessary.
so if you have idea, please share.

**Comment by OTKRyu** [comment]
i think the location that imported model exists is one of various options.

**Comment by mhs4670go** [comment]
I think it is sufficient to ask the user to select output path directly without default setting. If the extenion is actually used later, it will become more clear which one is better.

**Comment by OTKRyu** [comment]
This issue already developed, so i close this issue
