### ISSUE TITLE
Develop EXECUTOR TOOLSET API for local

### ISSUE THREAD

**Issue by YongseopKim** [Samsung/ONE-vscode#454]
Let's develop EXECUTOR TOOLSET API for local.

Plan
- 4/11 discussion
- 4/15 done to design/draft(impl+test)
- 4/22 Completed

**Comment by YongseopKim** [comment]
the `discussion` means that we need to discuss whether the rough(naive) plan is right or wrong.

**Comment by YongseopKim** [comment]
Tasks & Assignees
- UI: @jyoungyun 
- API: @YongseopKim 
- Backend:  @hyunsik-yoon

**Comment by YongseopKim** [comment]
This API should
- run the internal infer tool
- run the other NN model like tflite

/cc @yunjayh and @struss .

**Comment by hyunsik-yoon** [comment]
We've changed UI.
So how about close this and create a new one?

**Comment by hyunsik-yoon** [comment]
Let me close this issue.
