### ISSUE TITLE
Develop COMPILER TOOLSET API for local

### ISSUE THREAD

**Issue by YongseopKim** [Samsung/ONE-vscode#455]
Let's develop COMPILER TOOLSET API for local.

Plan
- 4/11 discussion
- 4/15 done to design/draft(impl+test)
- 4/22 Completed

**Comment by YongseopKim** [comment]
the `discussion` means that we need to discuss whether the rough(naive) plan is right or wrong.

**Comment by YongseopKim** [comment]
Tasks & Assignees
- UI: @jyoungyun 
- API: @YongseopKim 
- Backend:  @hyunsik-yoon

**Comment by hyunsik-yoon** [comment]
> 4/15 done to design/draft(impl+test)
> 4/22 Completed

Regarding implementation, I wonder the scope of this work.

Until 4/22, what function/method should we implement?
My guess is that basic goal is to enable these.

- list installed toolchains
- compile 

and others are stretch goal (until 4/22).

Please let me know if we need to implement more.

**Comment by jyoungyun** [comment]
Requirement from UI

**install**
* Get available(but not installed) package list
* Request to install package with some id(?) from package list

**search for installed package**
* Get installed package list with information
   * backend name
   * version
   * type(debian or docker image)
   * installed date
   * official(or nightly) 
   * some id(?)
* Get dependency package information with some id(?)
   * dependency packages name with version

**Comment by hyunsik-yoon** [comment]
https://github.com/Samsung/ONE-vscode/issues/569 will replace this issue.
