### ISSUE TITLE
Develop Backend driver for simulator

### ISSUE THREAD

**Issue by YongseopKim** [Samsung/ONE-vscode#456]
Let's develop backend driver for simulator.

**Comment by YongseopKim** [comment]
We have to discuss what the `bakcend driver` exactly is. What is output of the backend driver? What is the simulator?

**Comment by YongseopKim** [comment]
What is the plan for this issue?

**Comment by YongseopKim** [comment]
related issue: https://github.com/Samsung/ONE-vscode/issues/456

**Comment by YongseopKim** [comment]
@yunjayh I'm wondering that this task is a task of value-test? or execution?

**Comment by yunjayh** [comment]
Honestly, I confused this issue with # 458 (EXECUTE npu model on simulator)...

**Comment by YongseopKim** [comment]
@yunjayh and @struss 
- [ ] schedule this task until 4/29 with the smaller separated tasks

Tasks as I think
- Introduce backend driver like `onecc backend-driver` in ONE officially
- Before introducing it officially, let's use exec API(landed soon in the future) directly -> https://github.com/Samsung/ONE-vscode/issues/454
- After introducing it officially, let's use it

**Comment by YongseopKim** [comment]
Related issue: https://github.com/Samsung/ONE-vscode/issues/312

**Comment by YongseopKim** [comment]
@struss and @yunjayh can we close this?

**Comment by yunjayh** [comment]
I'll make another issue that track rest of https://github.com/Samsung/ONE-vscode/issues/456#issuecomment-1102168801. Then, this issue could be closed. :D Thank you!
