### ISSUE TITLE
EXECUTE npu model on simulator

### ISSUE THREAD

**Issue by YongseopKim** [Samsung/ONE-vscode#458]
Let's develop to EXECUTE npu model on simulator.

**Comment by YongseopKim** [comment]
On UI, we can see the npu model and we can click the model by the right button. And we can choose `execute` and it can execute to run npu model on simulator.

**Comment by YongseopKim** [comment]
What is the plan for this issue?
- 4/29(Fri) completed but release day so that this issue should be done before the release day.
- 4/27(Wed) completed
- 4/22(Fri) TBD
- 4/20(Wed) TBD
- 4/15(Fri) TBD

**Comment by yunjayh** [comment]
The sub tasks in my mind are these.

* Define Backend API for execution simulator
* Show execution button on right click to npu model
* Invoke simulator via backend API (with default option, such as auto random input generation) and print console log

While we listed the works to do, we assumed EXECUTOR TOOLSET API has to be completed before it start. I'm wondering where do we need the toolset api..

**Comment by hyunsik-yoon** [comment]
> On UI, we can see the npu model and we can click the model by the right button. And we can choose `execute` and it can execute to run npu model on simulator.

Currently, we don't have `execute` menu on tvn file. There are `run value test`, `measure performance`, `measure memory`.
I guess this task is for `run value test`?
Or... is `execute` is temporary menu to enable invoking simulator during April?

**Comment by hyunsik-yoon** [comment]
> AFAIU, no. This task is for just running.

Thinking about this scenario, we don't have ONE command to run a simulator (https://github.com/Samsung/ONE-vscode/issues/457#issuecomment-1094638254) and it will take some time for us to put the new ONE command into ONE _official_ release. (@struss @yunjayh, we should move fast)

For plan B, ONE has `one-profile` for profiling. Maybe we can run `one-profile` for this issue.

**Comment by YongseopKim** [comment]
ONE command is necessary? Backend and Toolchain API can support this.

**Comment by yunjayh** [comment]
Sorry but I'm not clear about `toolchain API`.. Could you briefly explain what backend or executor `Toolchain API` will cover? 

Let's assume a user chose a executor to run model. What will the API does?

 * via API, the extension gets command to run model. 
 * to execute model, the extension passes the arguments(such as model path, input file path, etc.) to API.

**Comment by YongseopKim** [comment]
Related: https://github.com/Samsung/ONE-vscode/issues/457#issuecomment-1097509115

**Comment by YongseopKim** [comment]
As we reach a conclusion about tools for simulator, let's make an issue on the private repo. @yunjayh @hyunsik-yoon

**Comment by YongseopKim** [comment]
This can be done by https://github.com/Samsung/ONE-vscode/issues/456. We can consider this as a result of https://github.com/Samsung/ONE-vscode/issues/456.

/cc @yunjayh and @struss

**Comment by yunjayh** [comment]
As `>ONE: infer`, this feature is now supported. The rest of the work about executing npu model on simulator, which is concluded to use `one-infer`, will be discussed in #456 .
