### ISSUE TITLE
[UX] Add Executor View

### ISSUE THREAD

**Issue by jyoungyun** [Samsung/ONE-vscode#461]
Let's add executor view on ONE view.

The detail job to be performed for this sprint:
- [ ] Add executor view (#471)
- [ ] ~~Add refresh button to the right top of executor View~~

Related issue: #453

**Comment by struss** [comment]
on Executor, I think we need specify type of executable model type on each. and also, we need add button to add more executor.

**Comment by jyoungyun** [comment]
We do not need refresh button on executor view. So I remove the item.
