### ISSUE TITLE
Design & Develop cfg editor UI

### ISSUE THREAD

**Issue by llFreetimell** [Samsung/ONE-vscode#464]
### What?

Let's create `cfg` editor!

![image](https://user-images.githubusercontent.com/24720192/164225261-66b1445c-97da-4cb0-b26a-0b858703e797.png)
**(Above image is just an example, detailed UI would be improved on and on)**

### Related PRs

- #496 
- #497

**Comment by YongseopKim** [comment]
Are we able to consider this task as a task of https://github.com/Samsung/ONE-vscode/issues/300?

**Comment by llFreetimell** [comment]
I think we can :)

**Comment by llFreetimell** [comment]
### Feature Requests

Following requests are collected from some of real users.
These items would be considered from next milestones :)

- Displaying easy option name on cfg editor
- Something for "Optimize/Quantize is started from circle, not pb/onnx/tflite"

**Comment by llFreetimell** [comment]
Done!
