### ISSUE TITLE
Let's define and schdule for `ONE-context-explorer` and `ONE-context-explorer-detail` views

### ISSUE THREAD

**Issue by YongseopKim** [Samsung/ONE-vscode#476]
- [ ] Define this task: ~4/14(Thr)
- [ ] Divide/Separate this task and schedule: ~4/15(Fri)
    - Maybe it's like the below things?
    - UI Tasks: task0(M1), task1(M2), ...
    - Internal Impl Tasks for UI: task0(M1), task1(M2), ...
- [ ] Make issues and assign on our ONE-project

/cc @Samsung/one-vscode

**Comment by dayo09** [comment]
(Suggestion)
About the naming for those two views we discussed,
how about 'explorer view' and 'detail view' ?

**Comment by dayo09** [comment]
#### Things to concern

If we are going to regard all tflite, onnx, ... model files as a 'base model' and npu model file as 'target model', our extension will be not very extensible for other model compiler usages.

For example, a model compiler who basically want to do onnx to tflite jobs, it would not work properly.

Therefore, I suggest the concept of 'base model'. Let's make user to select a 'base model' extension and let the 'explorer' only handles them and the 'detail view' to collect other files.
We may start by blocking other options than 'tflite' to make our jobs rather easy.

**Comment by jyoungyun** [comment]
First of all, we need to discuss whether we support to convert onnx to tflite in our ONE-vscode. How about talking on next Monday about this subject?

**Comment by dayo09** [comment]
> First of all, we need to discuss whether we support to convert onnx to tflite in our ONE-vscode.

My suggestion was based on its extensibility, rather than the actual support. I heard that our extension kinda meant to support the other compilers.

**Comment by dayo09** [comment]
I agree. I am closing this on behalf of other members.
