### ISSUE TITLE
Add initial version of file view

### ISSUE THREAD

**Issue by hyunsik-yoon** [Samsung/ONE-vscode#494]
Let's add an initial version of file view.

Features to be implemented are as follows:
- Basic 
  - [x] Show tflite files and their directory #505
  - [x] Show cfg file under tflite file #505
  - [x] Clicking cfg file will open cfg editor panel
- Run onecc
  - [x] #524
    - [x] Clicking 'Run' will run onecc
  - [ ] Newly created tvn file after compilation will show inside view.
- Creating a new cfg
  - [ ] show quickpick for path. User enters path for new cfg
    - Note: cfg in the view is shows under tflite. So path should be entered by user. (default path is the path where tflite is located)
  - [ ] show cfg under tflite and show cfg edit panel of which input tflite path is already entered.

**Comment by hyunsik-yoon** [comment]
/cc @Samsung/one-vscode  @llFreetimell 
Please find the UI for 'Creating a new cfg'. It is a bit _different_ from what we've discussed during online meeting.

@dayo09 is writing `Basic` feature. I believe that some part of `Run onecc` and `Creating a new cfg` can be done. Anyone can join this work. 😸

**Comment by hyunsik-yoon** [comment]
/cc @Samsung/one-vscode  @llFreetimell 
Please find the UI for 'Creating a new cfg'. It is a bit _different_ from what we've discussed during online meeting.

@dayo09 is writing `Basic` feature. I believe that some part of `Run onecc` and `Creating a new cfg` can be done. Anyone can join this work. 😸

**Comment by dayo09** [comment]
@hyunsik-yoon Basic features are now all supported by the draft. I will split them up and make PR.

**Comment by jyoungyun** [comment]
> Please find the UI for 'Creating a new cfg'. It is a bit different from what we discussed during online meeting (4/25 10:30AM).

https://github.sec.samsung.net/RS7-RuntimeNTools/secret/issues/187#issuecomment-1479490

I posted several days ago. I have thought the way to create new cfg file like a gif in my comment.
(Add icons to model file, Click the icon, Create a new file and show the cfg editor.)
Is it not enough?

**Comment by dayo09** [comment]
cc @jyoungyun 
@hyunsik-yoon and I shared an idea offline.
This is a summary.

#### 'Create' : generate config file. path is decided (same directory as model) / name is given by user.
Basically, `create` icon generates cfg file within the same directory. 
Detailed UI follows jyoungyun's idea.

(Sorry for using korean, I attach her origianal comment)
```
### [N] 을 선택했을 때 (새로운 vscfg 추가)
ONE explorer 에는 모델 아래에 새로운 파일이 추가되고 사용자가 이름을 저장할 수 있도록 활성화됨.
* 사용자가 저장했을 경우: 화면 우측(editor)에 vscfg editor 가 보여짐
example)
   - 생성된 이후의 directory hierarchy
* 사용자가 저장하지 않았을 경우: 무시
```

The below are the features to be considered now and implemented in the future, not for the demo.

#### Additional Support: Pair a config file with a model in a farway directory
We will allow users to locate a model file in a different directory too.
For this case, we add interface to add model path by 'insert'.

#### Additional Support: Shortened path
Shows tflite/cfg file paths with collapsed/shortened directory path view.
```
  >  inception_v3_2023/220313_from_model_team/
       v [M] a_model.onnx           [N] [I]
Instead of
   > inception_v3_2023
     v 220313_from_model_team
       v [M] a_model.onnx           [N] [I]
```
