### ISSUE TITLE
Define rule for logger

### ISSUE THREAD

**Issue by hyunsik-yoon** [Samsung/ONE-vscode#562]
We need some rule when to use logger and how to use.

For example, questions like "do we need to replace all console.out to logger.outputLine()?" should be answered.

@dayo09 raises the following question at https://github.com/Samsung/ONE-vscode/pull/559#discussion_r864577405

-----
(Q) Actually, I wonder why this line is critical to change. Is there any reason to share the same logger? The logger firstly looked like a log format provider. But it isn't? 

1. If we need to use the same logger across our vscode extension, why don't we provide a global context?
2. If loggers are not to be shared, why don't we just make it disposable as our inner project does?

I find it is designed to uses createOutputChannel('ONE-VSCode'), but I cannot see the difference between new Logger to shared logger.

**Comment by dayo09** [comment]
Resolved by #663 :-D
