### ISSUE TITLE
[Release] Create release action workflow

### ISSUE THREAD

**Issue by jyoungyun** [Samsung/ONE-vscode#571]
## What

Let's create release action workflow.

## How

- Use `workflow_dispatch` for manual trigger
   - needs release tag
- Create release issue
- Check license
- Check copyright
- Check build test
- Check unit test
- Create vsce package
- Create release tag
- Create release note

**Comment by llFreetimell** [comment]
Would you add "Check License for Release" ?
For now, only license checker for PR is implemented, but license checker for Release would be implemented in the near future.
But we can go with current license checker for PR because there are nothing special :)

**Comment by jyoungyun** [comment]
### Release information

- Not working `major.minor` version
   - According to [guideline](https://code.visualstudio.com/api/references/extension-manifest#fields), this version follows the [SemVer](https://semver.org/). And `SemVer` has a `MAJOR.MINOR.PATCH` format. So all vscode extension must follow the `MAJOR.MINOR.PATCH` format.
   - Error
      ```
      $ vsce package 0.1
      Executing prepublish script 'npm run vscode:prepublish'...
      
      > one-vscode@0.1.0 vscode:prepublish
      > npm run compile
      
      
      > one-vscode@0.1.0 compile
      > tsc -p ./
      
       ERROR  Invalid version 0.1
      ```
- Version should be matched with [version in package.json](https://github.com/Samsung/ONE-vscode/blob/main/package.json#L5)
   - If not matched, it emits error like below.
   - Error
      ```
      ERROR  Command failed: npm version 0.1.0
      ```
