### ISSUE TITLE
[GUI] Configuration file Settings for ONE developers

### ISSUE THREAD

**Issue by yeeybook** [Samsung/ONE-vscode#58]
What
----
Let's help ONE developers to make `.cfg` files easier!

Features
----

- [x] Show File Explorer to get the path of model file
- [x] Able/Disable the tool with toggle button
- [x] Export completed `.cfg` file
- [x] Import existing `.cfg` file
  - Read options from file and show them
- [x] Run one-build with button

Examples
----
- You can select a tool in the `Tools` and set options in the `Options for [selected_tool]`.
- Different input types depending on the value of the option.
   - `Path of model file` : File Explorer button
   - `True/False` : Toggle button
   - `Others` : Text input

![image](https://user-images.githubusercontent.com/58547845/132321021-db6da688-6959-430e-b5b8-cc1ea3b5aa62.png)

![image](https://user-images.githubusercontent.com/58547845/132321532-21dfb949-043d-4e3b-bce1-d43f765e9b3e.png)

- You can disable the tool you don't need.

![image](https://user-images.githubusercontent.com/58547845/132321729-b0236c85-981c-4ca5-b3d5-c98371c4ec64.png)

Related Issues
----
- #10
- #24

Discussions
----
- Where to extract the completed `.cfg` file?
   - After setting all the options, `Export Configuration`  button will extract the `.cfg` file.
   - So we should set the default location where the file will be saved.
   - This is related to #45

**Comment by OTKRyu** [comment]
LGTM

**Comment by mhs4670go** [comment]
In `one-import-tf` and `one-import-bcq`, it would be better to make some options one combobox. 
`v1`, `v2` -> converter version
`graph_def`, `saved_model`, `keras_model` -> model format

**Comment by yeeybook** [comment]
> 1. In `one-import-tf` and `one-import-bcq`, it would be better to make some options one combobox.

Yeah it seems better!
![image](https://user-images.githubusercontent.com/58547845/132448061-2f69c65a-0470-425f-9dc8-c49b2c9d71c9.png)


> 2. If the input path is set, it is better to make the output path auto-complete. For example, if the input path is set to `path/to/inception.pb`, the output path automatically set to `path/to/inception.circle`. Plus, it would be also nice for output path to have a file explorer button as well so that the folder where users want to save the output path can be found.

Auto-complete output path depends on input path seems good!
We were also considering about output path thing.
Thank you for your idea :D

**Comment by OTKRyu** [comment]
almost every function in this issue, so i close this issue
