### ISSUE TITLE
[OneExplorer] Candidate Features (May 2022)

### ISSUE THREAD

**Issue by dayo09** [Samsung/ONE-vscode#584]
From 
#494 (Initial functionality) 
#541 (For the first demo)

### File creation
- [x] #579 

### File rename / move
- [x] #637 Rename on Create cfg (possibily onDidCreateFiles or its fiamily api)
- [x] #674 Rename file by right-clicking

### Auto-refresh
- (Child Issue) #598
- [x] #622 

### Search files over directory bound
- (Child issue) #644
- [x] #669

**Comment by hyunsik-yoon** [comment]
@dayo09 The following step may (or may not) be related to OneExplorer and also default compilation options. I will write not to forget. 🐱 

When a user creates a new cfg file,
- User presses button to create a cfg on OneExplorer.
- ONE-vscode asks user which backend will be used for this new cfg. 
- User selects a backend.
- New cfg will be created considering selected backend.
  - For example, if backend is onert, cfg would probably contain [import -> optimize -> pack]
  - Or if backend is npu, cfg would probably contain [import -> optimize -> quantize -> codegen]

(Found during discussion with @llFreetimell. /cc @Samsung/one-vscode )

**Comment by seanshpark** [comment]
> ONE-vscode asks user which backend will be used for this new cfg.

Q) As working with ONE, backend is optional, that is I just want to drop circle file(quantized or not). Will ONE-vscode not support such case?

**Comment by hyunsik-yoon** [comment]
> Q) As working with ONE, backend is optional, that is I just want to drop circle file(quantized or not). Will ONE-vscode not support such case?

That is very good point. We should definitely support such needs someday. However currently main scenario is for backend developers and UI flow considers such backend users.
IMHO, for now to handle circle file only, user can select backend and then modify created cfg only for circle file handing (e.g., deleting `[codegen]` section)

**Comment by seanshpark** [comment]
> IMHO, for now to handle circle file only,

I understand this situation.
What I want to say is that, for this `ONE-vscode` repo, we only can see this and packages from `ONE`, not the packages like NPU in our in-house repositories.

When we install `one-compiler` from https://github.com/Samsung/ONE/releases (like `one-compiler_1.20.0_amd64.deb`) there is no backend tools installed.

So, if we make the UI to select backend for mandatory, users cannot proceed.
Thus there is some confusion in logic. IMHO, we can (1) talk and implement this in in-house repo or (2) users can proceed without backend seletion.
Anyway you're the boss here to decide.

**Comment by hyunsik-yoon** [comment]
> So, if we make the UI to select backend for mandatory, users cannot proceed.
That is a good point. Maybe we can provide `circle` as well as the list of other installed backends. As you suggested user should be able to use their installed ONE tool too. I will put those into backlogs. Thanks.

**Comment by dayo09** [comment]
(Updated)
I have updated the candidate list with priority, moving some into June 2022.

**Comment by dayo09** [comment]
The listed jobs are done.
