### ISSUE TITLE
[Text Editor] configuration file settings in text editor

### ISSUE THREAD

**Issue by Seojeonguk** [Samsung/ONE-vscode#59]
# What?
It provides convenience to users who create cfg files using vscode (text editor).

# How?
 - Snippets
   - It is automatically completed by creating a prefix for each tool.
 - Codelens
   - First, a code lens will be provided at the top of each tool.
   - If you click on the corresponding codelens, you will be provided with an additional codelens for the sub-attributes.
   - If you press the code lens for each attribute, that code lens disappears.
   - If you want to see the hidden property again, press the tool's codelens.
 - Hover
   - This shows a list of options if you mouse over the names of each tool.

# Examples
 - Snippets
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/44386047/132448396-f8b5781d-770f-4589-b95f-bfd518fa3bbc.gif)
 - Codelens
![codelens](https://user-images.githubusercontent.com/44386047/132448474-f836b467-e5c0-4b0b-af71-6154943a6be8.gif)
 - Hover
![ezgif com-gif-maker](https://user-images.githubusercontent.com/44386047/133710458-b58f095b-6821-4627-bc11-7eaa82af13b8.gif)
 

# Features
- [x] Automatic completion function using snippets.
  - [x] one-build
  - [x] oncc
  - [x] each tools
- [x] Description of tools and attributes using Codelens
  - [x] Calculate the scope of the tool
  - [x] Provide codelenses for tools
  - [x] Command operation for the codelens of the tool
  - [x] Calculate the range of attributes you want to hide
  - [x] Provide code lenses for properties to hide
  - [x] Command for attributes to hide
- [x] Description of tools and attributes using Hover

Related Issues
 -  #43
 -  #44
 - #243 

## Reference
- Snippets
  - user guide : https://code.visualstudio.com/docs/editor/userdefinedsnippets
  - example : https://github.com/microsoft/vscode-extension-samples/tree/main/snippet-sample
- Codelens
  - user guide : https://code.visualstudio.com/blogs/2017/02/12/code-lens-roundup
  - example : https://github.com/microsoft/vscode-extension-samples/tree/main/codelens-sample

**Comment by seanshpark** [comment]
Closing as not active. Feel free to reopen if needed.
