### ISSUE TITLE
Still show progress window even if the compilation fails

### ISSUE THREAD

**Issue by jyoungyun** [Samsung/ONE-vscode#635]
## What

The progress window still shows even if the compilation fails.

### prerequisite

- Wrong cfg file
```
[one-build] # Correct: [onecc]
...
```

### Test

1. Open ONE container
2. right click in wrong cfg on One Explorer view
3. Run

## Expect

When the compilation fails, the progress window closes.

## Actual result

When the compilation fails, the progress window continues to show.

**Comment by hyunsik-yoon** [comment]
I will check this later.

**Comment by hyunsik-yoon** [comment]
Solved.
