### ISSUE TITLE
[OneExplorer] Find config file from any directory

### ISSUE THREAD

**Issue by dayo09** [Samsung/ONE-vscode#644]
## What?

Let's find configuration files from any directory.

Currently, OneExplorer only searches the configuration for the model within the same directory.
Let's find the configuration files within the workspace. 

### Details 
- find the configuration files within the workspace. 
- show the config file's name as it's relative path. -> show only the name

### Related PRs
- #669 
- #672
- #681

**Comment by hyunsik-yoon** [comment]
I realized that when `input_path` is relative path, it is relative to `onecc`'s working directory.
Only by looking into `input_path` in cfg file, it seems very difficult to find the base model, doesn't it? 😿 

```shell
$ pwd
/home/eric/m/src/model/onecc-test 

$ tree
.
├── cfg
│   └── inception_v3_conv2d.0to128.cfg
├── inception_v3
│   └── 2020-01-31
│       └── inception_v3_conv2d.0to128.tflite
└── trash

4 directories, 2 files

$ cat cfg/inception_v3_conv2d.0to128.cfg
[onecc]
one-import-tf=False
one-import-tflite=True
one-import-bcq=False
one-import-onnx=False
one-optimize=True
one-quantize=True
one-pack=False
one-codegen=True

[one-import-tflite]
input_path=./inception_v3/2020-01-31/inception_v3_conv2d.0to128.tflite
output_path=./trash/model.circle

[one-optimize]
input_path=./trash/model.circle
output_path=./trash/model.opt.circle
all=True
remove_redundant_transpose=True

[one-quantize]
input_path=./trash/model.opt.circle
output_path=./trash/model.q8.circle
granularity=channel

[one-codegen]
backend=tv2
command=-o inception_v3/2020-01-31/model.tvn --DSP-quota 64K ./trash/model.q8.circle

$ onecc -C ./cfg/inception_v3_conv2d.0to128.cfg
Recording 0'th data
Recording 1'th data
Recording 2'th data
Recording finished. Number of recorded data: 3
<< compiling message was omitted >>

$ tree
.
├── cfg
│   └── inception_v3_conv2d.0to128.cfg
├── inception_v3
│   └── 2020-01-31
│       ├── inception_v3_conv2d.0to128.tflite
│       └── model.tvn
└── trash
    ├── model.circle
    ├── model.circle.log
    ├── model.opt.circle
    ├── model.opt.circle.log
    ├── model.q8.circle
    └── model.q8.circle.log

4 directories, 9 files
```

**Comment by dayo09** [comment]
> I realized that when input_path is relative path, it is relative to onecc's working directory.

Oh, I have assumed that the file paths in config file are relative paths of **the config file's directory**. I thought it's natural.

However, as you mentioned, it seems that it calculate paths based on **cwd**. 

I will change ConfigObject behavior, but I don't know which behavior is better.
I support that "the file paths in config file are relative paths of **the config file's directory**" I want to ask other's opinion about this.

**Comment by dayo09** [comment]
@hyunsik-yoon I examined the point and found out that your `OneccRunner` runs onecc on `config file's directory`.
I think that's why I didn't confront an error while testing the current PR.

https://github.com/Samsung/ONE-vscode/blob/5c3c1f636c6ac115b2c8fb46d49bf85fd66c660d/src/OneExplorer/OneExplorer.ts#L477

So it resolved the problem about cwd, and it seems okay.

BTW, as you mentioned on the other issue, our extension calculates the path based on config and the onecc doens't. That is needed to be resolved too. Let's discuss about that on the meeting

_Originally posted by @dayo09 in https://github.com/Samsung/ONE-vscode/pull/681#discussion_r878831742_

**Comment by dayo09** [comment]
In the end, https://github.com/Samsung/ONE/issues/9159 will be proceeded - the option for 'cfg-based path parsing' will be added to onecc, and it will become a default in the future. So we can assume that our OneExplorer's behavior to be a norm. I am proceeding with the PR.
