### ISSUE TITLE
Investigate and apply logging

### ISSUE THREAD

**Issue by hyunsik-yoon** [Samsung/ONE-vscode#662]
We are using `Logger` and `console.log`.
Let's find the answer for the following:
- How are they different?
- What is good way?

**Comment by hyunsik-yoon** [comment]
After installing vsix files, I couldn't find where I see output of `console.log()`.

From https://stackoverflow.com/a/69216474,

> Just open vscode and go to menu "Help"->"Toggle Developer Tools" and the console is displayed on rigth window.

I tried and found the log there. The messages are mixed with messages from other extensions.

Screen shot ===> [consoleLog.zip](https://github.com/Samsung/ONE-vscode/files/8706963/consoleLog.zip)

So `console.log()` is for **debugging-purpose**, not good for end-user.

Anyways, for our development purpose, it would be better to use some prefix, e.g., `one-vscode` so that we can filter messages in "Toggle Developer Tools".

**Comment by hyunsik-yoon** [comment]
Also after installing vsix files, I found weird things.

There are two `ONE-vscode`  output channel.     =========> [Screenshot : onevscode.logging.zip](https://github.com/Samsung/ONE-vscode/files/8707029/onevscode.logging.zip)

When we call `new util.Logger()`, new output channel is created. So we should consider, e.g., singleton for Logger.

**Comment by hyunsik-yoon** [comment]
https://nodejs.org/en/docs/guides/dont-block-the-event-loop/ mentions that
node js has only a small number of threads:
1. one for event loop
  - this is where most code runs
2. others for worker pool
  - for heavy stuffs such as DNS  lookup, file read/write

I think logging is done by event loop thread. Therefore there would not be a typical multi-thread issue.

**Comment by hyunsik-yoon** [comment]
#### Let's not use `console.log()`.
#### Let's use `Logger.outputWithTime()`

I will make PR for this.

**Comment by hyunsik-yoon** [comment]
More opinions: 
- tag: https://github.com/Samsung/ONE-vscode/pull/682#pullrequestreview-979347813
- rename: https://github.com/Samsung/ONE-vscode/pull/682#discussion_r8769117314
- Android example: https://github.com/Samsung/ONE-vscode/pull/682#issuecomment-1132398728

**Comment by hyunsik-yoon** [comment]
### Typical logging foirmat of vscode and vscode extensions
- `time module tag msg` where tag is, e.g., `info`, `warning`, etc.

**Comment by hyunsik-yoon** [comment]
Can we get function name or class name automatically?

1. use `callee` -> but this does not work in `strict` mode. 
https://stackoverflow.com/questions/1013239/can-i-get-the-name-of-the-currently-running-function-in-javascript

However we got this error.
```
'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions 
or the arguments objects for calls to them 
```

or 

https://stackoverflow.com/a/48613926
![image](https://user-images.githubusercontent.com/63768207/169957900-ea5e108c-2aa8-4856-bc40-f33b838af536.png)

we have this line:
https://github.com/Samsung/ONE-vscode/blob/a3d808c3d7186234bfd364af94849c087306d7c7/tsconfig.json#L11


2. use 'new Error()`

This is shown in https://adrianhall.github.io/cloud/2019/06/30/building-an-efficient-logger-in-typescript/ 

But question is.... should we do such thing to log a message?

**Comment by hyunsik-yoon** [comment]
```
function getFuncName() {
    let e = new Error();
    return e.stack!.split('\n')[3].trim().split(' ')[1];

}

function log(msg: string) {
    console.log(`[${getFuncName()}] ${msg}`);
}

function compile() {
    log("starting.....");
}

compile()
```

will print

```
"[compile] starting....." 
```

**Comment by YongseopKim** [comment]
I don't think the `TAG` means each function name. I do `TAG` means a kind of module or component. So I'd you to use declare manually not automatically.
