### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE-vscode#69]
Let's add unit  testing and enable it in CI

**Comment by YongseopKim** [comment]
Let me take!

**Comment by YongseopKim** [comment]
- [ ] Decide an unittest framework
- [ ] Introduce the fw
- [ ] Add unittests

**Comment by YongseopKim** [comment]
draft: https://github.com/Samsung/ONE-vscode/pull/328

**Comment by YongseopKim** [comment]
draft is done. I'll separate it and push soon. /cc @Samsung/one-vscode

**Comment by YongseopKim** [comment]
The draft includes the basic tests(the minimal positive tests)
- ui tests are excluded because there is no decision to handle ui tests

**Comment by YongseopKim** [comment]
In the future, we need to
- separate ts classes to one that uses vscode-api and others that don't
- and then, separate ts tests like the way

**Comment by YongseopKim** [comment]
Done
