### ISSUE TITLE
[UX/Compile] Make default config files with default compile options

### ISSUE THREAD

**Issue by YongseopKim** [Samsung/ONE-vscode#691]
Let's make default config files with default compile options.
- [ ] Introduce one-cmd like `one-init` in ONE: https://github.com/Samsung/ONE/issues/9153
- [ ] Support default compile options broadly

It is related to https://github.com/Samsung/ONE-vscode/issues/300.

**Comment by YongseopKim** [comment]
Issues related optimization options
- https://github.com/Samsung/ONE/issues/5784
- https://github.com/Samsung/ONE/issues/8570
- https://github.com/Samsung/ONE-vscode/issues/303

**Comment by llFreetimell** [comment]
This issue is under progress by @hyunsik-yoon, so this may be closed for now :)
Thanks for your effort T.T
