### ISSUE TITLE
Find default inputs and outputs of onnx model

### ISSUE THREAD

**Issue by hyunsik-yoon** [Samsung/ONE-vscode#693]
With onnx model, user needs to enter the names of inputs and outputs of the model.
If we provide default inputs and outputs of onnx model, it would make usability better.

Things to do:

- [ ] check why _one-import-tflite_ does not need inputs and outputs list but _one-import-onnx_ needs
- [ ] design how to introduce this feature
- [ ] implementation (TBD)

**Comment by hyunsik-yoon** [comment]
Why I think we need to do this task?

I checked one-import-onnx:
```
$ /usr/share/one/bin/one-import-onnx --help
usage: one-import-onnx [-h] [-v] [-V] [-C CONFIG] [-i INPUT_PATH] [-o OUTPUT_PATH] [-I INPUT_ARRAYS] [-O OUTPUT_ARRAYS] [--model_format MODEL_FORMAT]
                       [--converter_version CONVERTER_VERSION] [--unroll_rnn] [--unroll_lstm] [--save_intermediate]

command line tool to convert ONNX to circle

optional arguments:
  -h, --help            show this help message and exit
  -v, --version         show program's version number and exit
  -V, --verbose         output additional information to stdout or stderr
  -C CONFIG, --config CONFIG
                        run with configuation file
  --unroll_rnn          Unroll RNN operators
  --unroll_lstm         Unroll LSTM operators
  --save_intermediate   Save intermediate files to output folder

converter arguments:
  -i INPUT_PATH, --input_path INPUT_PATH
                        full filepath of the input file
  -o OUTPUT_PATH, --output_path OUTPUT_PATH
                        full filepath of the output file
  -I INPUT_ARRAYS, --input_arrays INPUT_ARRAYS
                        names of the input arrays, comma-separated
  -O OUTPUT_ARRAYS, --output_arrays OUTPUT_ARRAYS
                        names of the output arrays, comma-separated
  --model_format MODEL_FORMAT
  --converter_version CONVERTER_VERSION
```

Today people suggested me to check existing cfg files and I found that cfg does not have `INPUT_ARRAYS`. 

I also ask @seanshpark and he mentioned that that option is not used any more. :-)

**Comment by hyunsik-yoon** [comment]
I've heard that pb file also does not need input array when `tf.__version__ > 2`.

I wonder if we need to support tf version 1....

**Comment by seanshpark** [comment]
> I wonder if we need to support tf version 1....

@lemmaa , any information on this?

**Comment by lemmaa** [comment]
tf 1.x still exists in our customer requirements. We will have to keep it going for the time being.

**Comment by hyunsik-yoon** [comment]
@seanshpark updated this issue with TF.

Please refer to https://github.com/Samsung/ONE-vscode/pull/740#discussion_r885229372 

Let me close this issue.
