### ISSUE TITLE
[CfgEditor] Upgrade to whole new UI

### ISSUE THREAD

**Issue by llFreetimell** [Samsung/ONE-vscode#698]
### What?

Current CfgEditor is not that good to users.
Let's upgrade current UI to brand new UI!

### How?

For detailed **change previews**, those can be checked at draft PR or following related PRs.

- UI Upgrade
  - Change Step progress bar
  - ~~Change summary panel UI~~
  - Move 'import model type' into 'Import' step
  - Substitute import/codegen/profile step UI
- Feature Upgrade
  - Apply changes from cfg editor to cfg file
- Etc
  - Bugfix
    - `onecc` is not recognized

---

#### Draft

- #697 

#### Todo/Done

- #719 
- #721 
- #740 
- #750 
- #755 
- #764 
- #765 
- #776

**Comment by hyunsik-yoon** [comment]
Yesterday, I was briefly thinking about how to make value-test panel and
I realize that look'n'feel of value-test panel must be similar to that of cfg editor.
That means that it would be great if each UI component in cfg editor could be easily reused by other panels. :-)
We could reuse at component level or source code level.. either way would be fine. :-)

**Comment by llFreetimell** [comment]
Done!
