### ISSUE TITLE
Format command ids

### ISSUE THREAD

**Issue by dayo09** [Samsung/ONE-vscode#728]
## What?

Let's format our command names as 
`one.\<module\>.\<command\>`

1. `one.` prefix
- Use `one` instead of `onevscode` as our extension's official name is 'one'
2. `\<module\>.\<command\>`
- Currently, you can see that vscode defines their own commands as this.
  - workbench.view.earch (View: Show Search)
  - workbench.extensions.action.installExtensions (Extensions: Install Extensions)

#### Current command lists
```
onevscode.refresh-one-explorer ---> one.exploer.refresh
onevscode.create-cfg 
onevscode.flip-cfg-to-gui ----------> one.cfg-editor.open-gui
onevscode.flip-cfg-to-ini
onevscode.infer-model
onevscode.run-cfg
onevscode.rename-on-oneexplorer
onevscode.refresh-toolchain -------> one.toolchain.refresh
onevscode.install-toolchain
onevscode.uninstall-toolchain
onevscode.register-device ----------> one.devices.register 
onevscode.build
onevscode.import
onevscode.json-tracer
onevscode.configuration-settings
onevscode.toggle-codelens
onevscode.circle-tracer
onevscode.circle-graphview
onevscode.refresh-one-explorer
onevscode.refresh-toolchain
onevscode.install-toolchain
onevscode.register-device
onevscode.run-cfg
onevscode.rename-on-oneexplorer
onevscode.open-text-editor-on-one-explorer
onevscode.create-cfg
onevscode.uninstall-toolchain
onevscode.flip-cfg-to-gui
onevscode.flip-cfg-to-ini
```

## Why?
1. For our convinience 
-> There are basic operations like "add / move / delete" which one explorer / toolchain view/ device view will implement. Let's separate their namespace for convinience.

2. To have sync with the naming rule of other vscode commands.

**Comment by dayo09** [comment]
### Namespace decisions

It's clear about explorer/toolchain/device view's commands,
but it's hard to decide pre-existing function's workspace names.. Please suggest any ideas on this table.

Before | After
-- | --
onevscode.refresh-one-explorer | one.explorer.refresh
onevscode.create-cfg | one.explorer.createCfg
onevscode.run-cfg | one.explorer.run
onevscode.rename-on-oneexplorer | one.explorer.rename
onevscode.refresh-one-explorer | one.explorer.refresh
onevscode.open-text-editor-on-one-explorer | one.explorer.openTextEditor
  |  
onevscode.refresh-toolchain | one.toolchain.refresh
onevscode.install-toolchain | one.toolchain.install
onevscode.uninstall-toolchain | one.toolchain.uninstall
  |  
onevscode.register-device | one.device.register
  |  
onevscode.flip-cfg-to-gui | one.editor.openAsCfg
onevscode.flip-cfg-to-ini | one.editor.openAsIni
onevscode.toggle-codelens | ?
  |  
onevscode.build | ?
onevscode.import | ?
onevscode.json-tracer | ?
onevscode.configuration-settings | ?
onevscode.circle-tracer | ?
onevscode.circle-graphview | ?
onevscode.infer-model | ?



</body>

</html>

**Comment by hyunsik-yoon** [comment]
> `onevscode.toggle-codelens`

CodeLensProvider is in ONE-vscode/src/Editor/. I guess it's a part of editor.... How about `one.editor.toggleCodelens`?

likewise,
`onevscode.build` -> `onevscode.project.build`
`onevscode.import` -> `onevscode.project.import`
`onevscode.configuration-settings` -> `onevscode.config.show` ?
...
?

**Comment by dayo09** [comment]
@hyunsik-yoon Thanks for your opinions!

1. `one.editor.toggleCodelens` and `onevscode.project.build` sounds cool.
2. Actually, I don't know what `onevscode.import` does. Seemingly, it opens a cfg file... It might be not about project.
3. configuration-settings looks like to open a legacy editor view. (maybe one.editor.openAsCfgLegacy ?)

**Comment by dayo09** [comment]
@llFreetimell Could you give some opinion about those commands? (what they do, will they remain..)

command | field
-- | --
onevscode.import | (deprecate?)
onevscode.configuration-settings | (deprecate?)

**Comment by llFreetimell** [comment]
I think following five commands should be considered in the near future.

- Deprecation
  - onevscode.build
  - onevscode.import
  - onevscode.configuration-settings
- Remodeling
  - onevscode.json-tracer
  - onevscode.circle-tracer

So how about setting those field as `one.notdefined.*` and then deprecate or reset them later? :D

**Comment by llFreetimell** [comment]
And if you don't mind, I want to suggest following idea :)

- onevscode.flip-cfg-to-gui --> one.editor.openCfgWithCustom
- onevscode.flip-cfg-to-ini  --> one.editor.openCfgWithText

**Comment by dayo09** [comment]
[llFreetimell](https://github.com/llFreetimell)

Well, I just come up with this:

one.editor.open
one.editor.openAsText

**Comment by dayo09** [comment]
What do you guys think about the namespace?

backend or device?

@yunjayh @struss 

Before | After
-- | --
onevscode.register-device | one.(backend/device).register |
onevscode.infer-model | one.(backend/device).infer

**Comment by yunjayh** [comment]
`onevscode.infer-model` was first introduced for temporal use. `backend` will be more appropriate for now, because `infer` itself only depends on backend, not devices.

However, if we consider about long term usage of command `infer`, I think neither backend nor device, but execute... or something is better for its namespace. The `infer` command can be done on both `toolchain` and `device`. 

Would you like to remain current `infer` as `backend.infer` and change it including the namespace when full functions are intruduced?

**Comment by dayo09** [comment]
@yunjayh Yeah, sure :-D
Then, one.backend.infer. Thanks for your opinion.

**Comment by dayo09** [comment]
@struss gave me an opinion of `one.device.register` by knox chat.

**Comment by dayo09** [comment]
Done!
