### ISSUE TITLE
Idea collection for ONE developer supporting tools in VSCode

### ISSUE THREAD

**Issue by llFreetimell** [Samsung/ONE-vscode#8]
# ONE developer supporting tools in VSCode

Let's make ONE developers convenient by introducing many kinds of ONE developer tools!

This issue is created for overall discussion of the tools. For example, "Which item can we think of?" or "Is the function is really meaningful for developers?". **If some items are decided to be supported, they will be progressed as separate issue.**

## Candidate Features

Following candidates are

- not determined whether they are really possible or not
- not fixed whether they are really done like that

They are just candidates!

### Funtional requirements

- Visualization for various file type which includes ONE development data
    - json : Compatible with chrome tracing
    - csv : Indicates not only table, but also other kinds
    - dot
    - ...
- Embedding or automatic-opening chrome tracing
- Showing origin information in circle file with backend output

**NOTE** Examples for each file format will be added soon.

### Non-functional requirements

- When new type of file should be visualized, what we need to do is just adding visualization function for the new type of file.
- When visualization method is updated for some type, it should not affect the others. In other words, if visualization method for json is updated, then visualization method of csv, dot, etc should not be affected.
- Typing same path of the files should be minimized. For example, once the path for each files are saved in `.cfg` file, users do not need to enter the path everytime.

## Example Result

This is really simple example for easy understanding of overall concept.

![example_2](https://user-images.githubusercontent.com/24720192/130345056-a1ba09c4-c3e0-49ce-a6cb-831c95ba1339.png)

## References

- Simple extension examples : https://github.com/microsoft/vscode-extension-samples
- Advanced visualization in vscode examples : https://github.com/hediet/vscode-debug-visualizer/tree/master/extension

**Comment by llFreetimell** [comment]
## Candidate Feature - 1 : Show profiling json

Let's show following json pretty!

- [sample.profile.json.txt](https://github.com/Samsung/ONE-vscode/files/7046598/sample.profile.json.txt)

### Functionality candidates

- Show json pretty
- Zoom-in/Zoom-out
- If click, show detailed information
- Show sorted result by duration time
- If click origin information, show original circle node
- (To be added more)

**Comment by CODe1995** [comment]
@llFreetimell 
## How to read .cfg file?
In **python**, I know that a `.cfg` file can be read easily through [`ConfigParser`](https://docs.python.org/3/library/configparser.html),
but in **typescript**, I know that there is no other way to read a `.cfg` file other than general string parsing.
Can you tell me what language was used to import values ​​from the `.cfg` file and how did you get them?

**Comment by llFreetimell** [comment]
@CODe1995 

We used Python in ONE to import/read the values from `.cfg` file because `.cfg` file follows INI format.
I think typescript does not have such a general tool like `ConfigParser` :(
Javascript may have some elegant way to parse `.cgf` file but if not, we would find another way or make simple parser only for the `.cfg` file..!

**Comment by seanshpark** [comment]
Maybe https://www.npmjs.com/package/ini ?

**Comment by seanshpark** [comment]
https://www.npmjs.com/package/configparser too

**Comment by seanshpark** [comment]
> Show profiling json

From #13 issue, I assume #13 is related with `profiling json` task...

I've found https://github.com/catapult-project/catapult/tree/master/tracing from chrome project which is mirror of https://chromium.googlesource.com/catapult , which someone may already know...
This provides a python script `tracing/bin/trace2html` that converts profiling json to html file.
I think it would be relatively easier than developing from the scratch to embed HTML view component.
I don't know how as of now but I assume we can...

Our `sample.profile.json` file is converted to `4250289` bytes of html file;
This is the capture of it opened in my browser.

![image](https://user-images.githubusercontent.com/4616940/131443562-797fa1cb-f76c-4f82-a56f-428bd4120abc.png)

**Comment by llFreetimell** [comment]
@seanshpark 

> is the final goal of this task is to show graph like below to our vscode extension?

I cannot assure anything for now but in my mind, no that is not our final goal.
We can start with showing just like chrome tracing, but our final goal may be different with it :)

**Comment by seanshpark** [comment]
>  but our final goal may be different with it 

Can you describe more about it? or do we need more imaginations, discussions and stuff?

> We can start with showing just like chrome tracing

Hum... I don't have much experience with chome tracing so I may not distinguish fine distinctions.
Is chrome tracing like view one of our featiure? or just a stepping stone so we'll provide whole much different one?

**Comment by llFreetimell** [comment]
> Can you describe more about it? or do we need more imaginations, discussions and stuff?

Under imaginations and under discussions :)

> Is chrome tracing like view one of our featiure? or just a stepping stone so we'll provide whole much different one?

Maybe latter one seems correct but there is a still possibility to include former one too :)

**Comment by yeeybook** [comment]
@llFreetimell 
As the picture you showed, you specified `[one-dev-tool]` that indicates the path of the .json file,
but I can't find any tools like that.
So I'm wondering, **when** the path of the .json file will be specified in .cfg by **which** tool?

**Comment by yeeybook** [comment]
And also, is it right to express `[one-optimize]`, `[one-profile]` things as **tools**?😅
Or should I say them as **drivers**?

**Comment by llFreetimell** [comment]
@yeeybook
Before I answer, I want to let you know that the initial idea is almost abandoned because of some inconvenience in my mind.
And as this issue is so general that writing specific idea is little bit hard, I am planning to create another separate issues for each item :)
(In addition, I will close this issue in the near future!)

---

> when the path of the .json file will be specified in .cfg by which tool?

`.cfg` file is not generated by some tools, it is generated by user!
Therefore, I thought that path of `.json` file is specified by user, not tool :)

> is it right to express [one-optimize], [one-profile] things as tools? :sweat_smile: Or should I say them as drivers?

Hmm.. both of them seems okay for me :D

**Comment by yeeybook** [comment]
Well.. we're making an extension that helps users make a `.cfg` file more comfortable.
So we need to know which options will be written in `.cfg` file.
Therefore, I was curious about in which part the path of `.json` will be specified by user!
If you think my question is quite ambiguous, then I'll discuss about it more with team again :)

**Comment by yeeybook** [comment]
@llFreetimell 
Oh I see! Thank you for your answer :D

**Comment by llFreetimell** [comment]
I will close this issue because

- separate issues for each idea seems better
- Original idea in this issue is no more valid

So let's close this issue! :D
