### ISSUE TITLE
Hide unnecessary commands in command palette

### ISSUE THREAD

**Issue by yunjayh** [Samsung/ONE-vscode#839]
### WHAT

Let's hide unnecessary commands from command palette if it's accessible with some other buttons. features or internal functions.

### WHY

There are too many commands has been shown if user enter `ONE:` to command palette.

![image](https://user-images.githubusercontent.com/50489513/175250841-7956f125-ba2c-4834-acf5-c668bd5c5db7.png)

We are scheduling to do user study after the release, which is scheduled 30 June. It can be too bothering for the users who frequently use command palette while their development.

---

[Here](https://stackoverflow.com/questions/55270915/vs-code-extension-hide-commands-from-command-palette) is the way to hide them.

[Here is official guideline :)](https://code.visualstudio.com/api/extension-guides/command#controlling-when-a-command-shows-up-in-the-command-palette)

**Comment by yunjayh** [comment]
Here are lists of commands that could be found when  I entered `> ONE:` to command palette. (based on commit 64cbe76)
I categorized them in my own view. If there is any misunderstood, please let me know or feel free to fix it.

### Part Editor

command | hide or not
--- | ---
circle graph view | 
circle tracer | 

### one view

command | hide or not
--- | ---
Collapse Folders in ONE Explorer | 
Focus on ONE Explorer View | 
Refresh (one.explorer.refresh) | 
Create new ONE configuration | 
Open Containing Folder | 
Rename | 
Uninstall | 

### toolchain & toolchain view

command | hide or not
--- | ---
Foucs on Toolchain View | 
Install | 
Register | 
Refresh (one.toolchain.refresh) | 

### device view

command | hide or not
--- | ---
Focus on Target Devices View | 

### cfg editor

command | hide or not
--- | ---
Open cfg in GUI | 
Open cfg in GUI (legacy) | 
Open cfg in Text Editor | 
Open with Text Editor | 

### compile

command | hide or not
--- | ---
Run | 

### inference

command | hide or not
--- | ---
Infer | 

### legacy codes

command | hide or not
--- | ---
build | 
cfg import | 
json tracer | 
Toggle codelens for cfg |

**Comment by jyoungyun** [comment]
@yunjayh In my vscode, I couldn't see the `ONE: Foucs on Toolchain View` command. How did you make it show?

**Comment by yunjayh** [comment]
I didn't do anything, but I get into build mode and checked command palette with `> ONE:` typed. (the code was https://github.com/Samsung/ONE-vscode/commit/64cbe763db9e4d32294bc100baf81401695ee8b8 in main branch)

**Comment by yunjayh** [comment]
@jyoungyun From both build mode and vscix package, I could fuind `ONE: Focus on Toolchain View`. 😮

**Comment by seanshpark** [comment]
FYI: separated `Circle tracer` from `Partition Editor`

**Comment by dayo09** [comment]
@yunjayh  I don't think `ONE: uninstall` belongs to ONE Explorer. Maybe ONE Toolchain?

**Comment by dayo09** [comment]
> @yunjayh In my vscode, I couldn't see the ONE: Foucs on Toolchain View command. How did you make it show?

@jyoungyun It seems vscode create it by default. ONE Explore view and device view also have one. Let's just let them leave.

**Comment by yunjayh** [comment]
Every commands which are checked to hide is removed from command palette. Thank you for every contributors!! :tada:
