### ISSUE TITLE
Question about the file directory and `gitignore`

### ISSUE THREAD

**Issue by parkjisu6239** [Samsung/ONE-vscode#87]
## Question
I was going to run an extension on the main branch.
However, the `.vscode` is contained in the `gitignore`, so there is no `.vscode` folder in the repository.
So it can't be executed 😥 @seanshpark 

**_1. Could you upload the `.vscode` folder additionally?_**

**_2. May I know what kind of function the extension you're making is performing?_**

</br>

## Problem
This is the  `Draft` #52  I posted last time and the [link](https://github.com/SOSCON-TheONE/ONE-vscode-extension-prototype/tree/barchart) to the visualization function currently under development.

We use `React` for visualization. React was needed for selection of bar graphs or various interactions.
However, in the process of using React, **there have been many changes in file structure and defense.**

So I'm having a big problem `writing PR and draft` now. Our file structure can be seen [here](https://github.com/SOSCON-TheONE/ONE-vscode-extension-prototype/tree/barchart).

How can we solve this problem? If you have an idea, I'll accept it!

</br>

## The functions we created are as follows.
![image](https://user-images.githubusercontent.com/42528189/133377496-541ca8a9-7bd0-4fb8-b9f1-ef3da0711c60.png)

### Done

- Click `Load`, a file selection dialog will pop up
- You can `visualize` JSON files.
- `Zoom-in/Zoom-out` is possible.
- `pid`(GPU/CPU) usage is displayed.
- You can click on the bar to see `More info`.
- You can `open/close`  the panel.
- Fixed left bar
- Make the color a bit prettier
- When zoomed in/out, the scale is dynamically created/deleted.
- Zoom in with the `slider`.
- It's linked to the me in vcode. All elements follow the vscdoe theme color.

| dark+                           | light+                            | All vcode theme support.      |
| ------------------------------- | --------------------------------- | ----------------------------- |
| ![image](https://user-images.githubusercontent.com/42528189/133377624-d77d6f13-a4f7-4691-8ffd-6eb25486a1ad.png) | ![image](https://user-images.githubusercontent.com/42528189/133377649-862205d1-abd4-41d0-be7f-5739a8c6e05d.png) | ![image](https://user-images.githubusercontent.com/42528189/133377664-d67504ba-11fa-44a3-a5dd-508ea88568f0.png) |

(I'll leave a draft after I finish what I'm currently developing.)
</br>

**We hope this feature will really help one developers. So I hope this problem will be solved and merge.** 🙏

**Comment by seanshpark** [comment]
> However, the .vscode is contained in the gitignore, so there is no .vscode folder in the repository.

I've posted a PR

> May I know what kind of function the extension you're making is performing?

I'm working on #5 and currently landing codes in #68

**Comment by seanshpark** [comment]
> So I'm having a big problem writing PR and draft now. Our file structure can be seen here.

What I could say is that
- solve the problem one by one
- I'm new in vscode extension so my answers may not be correct(?)
- Make a new draft PR based on current `main` branch
   - Make a folder inside `src` and put your files in there (maybe ProfileViewer?) @llFreetimell any name for this?
   - Add command handler in extension.ts 
   - link command to your codes
- You can add questions on that draft PR
   - or you can add questions on your code with `file changed` tab

These are by thoughts about PRs
- one context per PR, that is, one purpose of objective in one PR; that is there can be lots of PRs; this will take time to land a huge change
- too many purpose makes understanding codes difficult
- one who wrote the code knows what one is doing but others' don't
- communicating by written word is very hard

**Comment by seanshpark** [comment]
Current CI checks for every PR a format checker and TypeScript compiler
- refer https://github.com/Samsung/ONE-vscode/tree/main/.github/workflows files
- you may need to install clang format checker with `sudo apt-get install clang-format-8`, in linux (Ubuntu 18.04/20.04)
- you can check format by running `bash infra/format` in linux console

**Comment by parkjisu6239** [comment]
I will close this issue because it has been discussed enough, and i have received the desired answer.
Additional content is here #93 .
