### ISSUE TITLE
Prepare `Release` and `Debug` build

### ISSUE THREAD

**Issue by hyunsik-yoon** [Samsung/ONE-vscode#870]
Currently we use _debug_ build to build ONE-vscode.
We now need to prepare _release_ build.

What is the difference between debug and release build with ONE-vscode?

- Debug build
  - put everything 
- Release build
  - remove '[debug]' log

What else?

Note: tsc compilers (https://www.typescriptlang.org/docs/handbook/compiler-options.html) does not seems to have optimization flgas.

**Comment by hyunsik-yoon** [comment]
### How to implement:
- env var? (like https://stackoverflow.com/a/59908595)
  - it won't work if ONE-vscode works after installing vsix.

**Comment by YongseopKim** [comment]
> What is the difference between debug and release build with ONE-vscode?

Q. Is it meaning that `npm run compile` **manually** removes `debug log` when it is built on release mode? or tsc compiler automatically removes `debug log`?

**Comment by hyunsik-yoon** [comment]
@YongseopKim,

For now, as far as release-build in a form of vsix does not show `debug` log, it would be great.

(Main purpose of running one-vscode by pressing F5 is for debugging... so we could consider it as debug-build.....)

**Comment by hyunsik-yoon** [comment]
> So, can I understand like below in ONE-vscode?
>  - a kind of debug build: run in debug mode -> Logger.debug() prints
>  - a kind of release build: install/run vsix -> Logger.debug() doesn't print

Yes. 

> And, we don't have to prepare release build? because vsix is done with release build.

I tried to find the difference between release build and debug build in case of JS or TS project. However, it seems that there are not many difference between them.

So I'd like to focus only on `Logger.debug()` in this issue.

**Comment by hyunsik-yoon** [comment]
Let me rename this.

**Comment by hyunsik-yoon** [comment]
logger.debug was handled well. Let me close.
