### ISSUE TITLE
[ToolchainEnv] Enable even workspace is not set yet

### ISSUE THREAD

**Issue by yunjayh** [Samsung/ONE-vscode#950]
### What

Let's enable many functions related to `toolchainEnv` even if the vscode workspace is not set yet.

### Why

`toolchainEnv` is independent to the workspace but only related with the execution environment.

**Comment by yunjayh** [comment]
AFAIU, the `WorkFlow` takes a workspace as its member variable, and execute the job commands with setting the `workspace`. as its `cwd`.

However, `Toolchain` related commands doesn't related with the working directory. So, let's set it as home directory.

**Comment by hyunsik-yoon** [comment]
> Let's enable many functions related to toolchainEnv even if the vscode workspace is not set yet.

When you meant by `many functions`, can you list those functions?

**Comment by yunjayh** [comment]
Following methods of `ToolchainEnv` class cannot be called if workspace is not defined.

  * `ToolchainEnv.execute` 
  * `ToolchainEnv.request`
  * `ToolchainEnv.prerequisites`
  * `ToolchainEnv.install`
  * `ToolchainEnv.uninstall`
  * `ToolchainEnv.compiler`

But all of the above methods are able to run independent to current working directory. That's why I fired this issue.

**Comment by hyunsik-yoon** [comment]
I guess that `ToolchainEnv.compile()` can be called when OneExplorerView is available ('available' means a case when workspace is set)

**Comment by jyoungyun** [comment]
I have confirmed that the above functions work without workspace through simple modification. Did you check the draft PR I suggested?

**Comment by yunjayh** [comment]
Thanks to @jyoungyun, #1002 solved this issue! :bow:
