### ISSUE TITLE
[CI] Introduce `PR/NO TEST` label

### ISSUE THREAD

**Issue by yunjayh** [Samsung/ONE-vscode#958]
For some draft prs, only adding some commands to `package.json` triggers license check, and it makes to comment by github action bot. 

Let's add `PR/NO TEST` label which skip github action for that pr.

If you have any opinion on this issue, feel free to comment and let me know. :smile:

### CAUTION

This label should be used only for draft PR. Some draft prs introduce new packages and it could cause license issue.
The contributor should check it carefully and use this feature.

**Comment by hyunsik-yoon** [comment]
I am not clearly sure about the problem you want to solve with this label. Do you want to remove comment by git bot? Or do you want to skip all tests?
One thing I believe is that draft should also go through as many tests as possible...

**Comment by yunjayh** [comment]
> I am not clearly sure about the problem you want to solve with this label. Do you want to remove comment by git bot after running tests? Or do you want to skip all tests?

I'd like to make to skip all the test if `PR/NO TEST` label has been set. The main purpose is reducing the git bot's comment if the author think it's unnecessary.

> One thing I believe is that draft should also go through as many tests as possible...

I totally agree with your opinion, but even though I think this feature is good to have. It will be optional to use and the author has responsibility to test his or her pr carefully.

**Comment by yunjayh** [comment]
Done.
