### ISSUE TITLE
[Circletracer] Deprecation Suggestion

### ISSUE THREAD

**Issue by llFreetimell** [Samsung/ONE-vscode#986]
@Samsung/one-vscode_committers 

I suggest following deprecation.
Please review following suggestion.

### What

- src/Circketracer.ts
    ```ts
    let disposableOneCircleTracer = vscode.commands.registerCommand('one.viewer.circleTracer', () => {
      Logger.info(tag, 'one circle tracer...');
      const options: vscode.OpenDialogOptions = {
        canSelectMany: false,
        openLabel: 'Open',
        /* eslint-disable */
        filters: {'Circle files': ['circle'], 'All files': ['*']}
        /* eslint-enable */
      };
      vscode.window.showOpenDialog(options).then(fileUri => {
        if (fileUri && fileUri[0]) {
          const circleToJson = decoder(fileUri[0].fsPath);
          Circletracer.createOrShow(context.extensionUri, circleToJson);
        }
      });
    });
    context.subscriptions.push(disposableOneCircleTracer);
    ```
- src/CircleReader
- media/Circletracer

### Why

- As `CircleGraph` is introduced, `CircleGraph` could represent circle file with `netron` engine.
- New features such as `CircleGraphCtrl` has now been implemented in `CircleGraph`.

---

#### Reference

- #955

**Comment by llFreetimell** [comment]
## 1st Notification

### Related Authors

- @yesfordev 
- @donggillee-dev 
- @CODe5753 

### Response Deadline

- 14th July, 2022

---

Please feel free to share your opinion for the suggestion :)

**Comment by llFreetimell** [comment]
## 2nd Notification

### Related Authors

- @yesfordev 
- @donggillee-dev 
- @CODe5753 

### Response Deadline

- 21th July, 2022
- This is the final call

---

Please feel free to share your opinion for the suggestion :)
If there are no response until above deadline, maintainers will decide about deprecation by authority..!

**Comment by CODe5753** [comment]
Sorry for the late response.
From my understanding, I understood that the same function as the existing one was newly implemented.
If this is correct, I agree with this proposal.

**Comment by donggillee-dev** [comment]
Sorry about the delay. 
I am totally okay with changing the code according to your opinion.
Please feel free to update with the deprecation.

**Comment by yesfordev** [comment]
Sorry for the late reply.
If it is true that the function to be replaced has been developed, it is okay to change the existing code.

Thank you :)

**Comment by llFreetimell** [comment]
## Final Result

### Decision

All authors of `Circletracer` agreed to deprecate on 14th July, 2022.

### Timeline

- 7th July, 2022 : @llFreetimell Suggests to deprecate.
- 14th July, 2022 : 1st notification is expired. 2nd notification announced.
- 14th July, 2022 : All of the authors agreed to deprecate without any objection.
- 18th July, 2022 : Deprecated by #1042.

### Legacy

Source codes for `Circletracer` can be found at following branch.
- https://github.com/Samsung/ONE-vscode/tree/release/0.2.0/src/Circletracer.ts
- https://github.com/Samsung/ONE-vscode/tree/release/0.2.0/src/Circlereader
- https://github.com/Samsung/ONE-vscode/tree/release/0.2.0/media/Circletracer

---

#### Comments

To @yesfordev @donggillee-dev @CODe5753

Although we deprecated `Circletracer`, it doesn't mean that `Circletracer` was useless.
Before `CircleGraph` is introduced, `Circletracer` was the only GUI tool for displaying circle file.
Furthermore, `Circletracer` was a pioneer for showing binary files in the vscode.

However, since `CircleGraph` is introduced, it's time to say good bye to `Circletracer` :cry: 
Furthermore, because of maintenance issue, I should have removed the source codes in `main` branch :sob: 
Please kindly understand me... :(

If you have any opinion, please feel free to leave some comments at anywhere you want!
Always welcome :)
