### ISSUE TITLE
Security-sensitive OS command

### ISSUE THREAD

**Issue by llFreetimell** [Samsung/ONE-vscode#988]
### What

Following codes are using security-sensitive OS commands.

https://github.com/Samsung/ONE-vscode/blob/aee748145b541dbc83141db05df718bd4c65ddb8/src/Execute/executeQuickInput.ts#L132

https://github.com/Samsung/ONE-vscode/blob/aee748145b541dbc83141db05df718bd4c65ddb8/src/Project/ToolRunner.ts#L178

Let's try to resolve this..!

### Reference

- https://rules.sonarsource.com/typescript/RSPEC-4721/

**Comment by hyunsik-yoon** [comment]
I tried the following:

```
$ cat ./askpass.sh 
#!/bin/bash
echo your_password

$ export SUDO_ASKPASS=$(pwd)/askpass.sh
$ sudo -k  # reset previous sudo cache

$ sudo ls  # this asks password
[sudo] password for eric:   # let's press ctrl-C

$ sudo -A ls  # with -A, sudo does not ask password since it receive password from running SUDO_ASKPASS
askpass.sh
```

So, what we can try could be

1. get password from GUI
2. create a temp script 
3. run `spawnSync('sudo -A ...')` with `SUDO_ASKPASS` envvar
4. right after running, make sure (and make sure again!!) to remove the temp script!!

Period from 2 to 4 should be very short. I guess we could run 3 in `async` function...?

```ts
async run() {
   spawnSync(...)
}

async runMain() {
   createScript(...)
   run()  // run this asynchronously
   makeSureRemoveScript(...)
}

```

ref: `-A` option in `man sudo` and https://stackoverflow.com/questions/12608293/how-to-setup-a-sudo-askpass-environment-variable

**Comment by jyoungyun** [comment]
I am worried that there should be a file with password if it's temporary....
Anyway I tried to apply this changes:

```
        const tempfile="temp.sh";
        cp.spawnSync(`echo "#!/bin/bash\necho ${process.env.userp}" > ${tempfile}`, {cwd: path});
        Logger.info(this.tag, `SUDO_ASKPASS=${path}/${tempfile} sudo -A ` + tool);
        this.child = cp.spawn(`SUDO_ASKPASS=${path}/${tempfile} sudo -A ` + tool, toolargs, {cwd: path, shell: true});
        cp.spawnSync(`rm ${tempfile}`);
```
Result:
```
[7/8/2022, 2:29:17 PM][ToolRunner][info] SUDO_ASKPASS=.../git/npu/ONE-example/temp.sh sudo -A aptitude
sudo: unable to run .../git/npu/ONE-example/temp.sh: **No such file or directory**
[7/8/2022, 2:29:17 PM][ToolRunner][info] child process exited with code 1
[7/8/2022, 2:29:17 PM][ToolRunner][info] Build Failed: 1
```

```
        const tempfile="temp.sh";
        cp.spawnSync(`echo "#!/bin/bash\necho ${process.env.userp}" > ${tempfile}`, {cwd: path, shell: true});
        Logger.info(this.tag, `SUDO_ASKPASS=${path}/${tempfile} sudo -A ` + tool);
        this.child = cp.spawn(`SUDO_ASKPASS=${path}/${tempfile} sudo -A ` + tool, toolargs, {cwd: path, shell: true});
        cp.spawnSync(`rm ${tempfile}`);
```
Result:
```
[7/8/2022, 2:32:37 PM][ToolRunner][info] SUDO_ASKPASS=.../git/npu/ONE-example/temp.sh sudo -A aptitude
sudo: unable to run /home/jyoung-linux/git/npu/ONE-example/temp.sh: **Permission denied**
[7/8/2022, 2:32:37 PM][ToolRunner][info] child process exited with code 1
[7/8/2022, 2:32:37 PM][ToolRunner][info] Build Failed: 1
```

When I tried this code, I couldn't create tempfile and change the file mode without `shell:true` option.

```
        const tempfile="temp.sh";
        cp.spawnSync(`echo "#!/bin/bash\necho ${process.env.userp}" > ${tempfile}`, {cwd: path, shell: true});
        cp.spawnSync(`chmod +x ${path}/${tempfile}`, {cwd: path, shell: true});
        Logger.info(this.tag, `SUDO_ASKPASS=${path}/${tempfile} sudo -A ` + tool);
        this.child = cp.spawn(`SUDO_ASKPASS=${path}/${tempfile} sudo -A ` + tool, toolargs, {cwd: path, shell: true});
        cp.spawnSync(`rm ${tempfile}`);
```

Finally, this code is working well but it needs `shell:true` option on all command line....

**Comment by hyunsik-yoon** [comment]
I created a draft for this and it works well.
The draft creates a script file that echos pw and removes the file right after running sudo. Anyway, the script file (permission 700) exists under a predefined directory for, say, 100 ms.

One issue is the location of password file. I am not sure it's OK to make a PR that has some hint of path of script file. What if some hacker knows the path of script file?

**Comment by hyunsik-yoon** [comment]
I discussed with @seanshpark @jyoungyun @llFreetimell with various way to solve this situation.
I think we can add code to verify command and arg before calling `spawn(... {shell:true})`.
@llFreetimell will discuss this with SE people.

**Comment by hyunsik-yoon** [comment]
I am trying to implement pipe with two spawn() call.
Refer to draft in internal repo 103.

**Comment by hyunsik-yoon** [comment]
All merged.
